### ISSUE TITLE
 Error in error binary package libattr1:i386 (installing skype)

### ISSUE THREAD

**Issue by guyr34** [ProfessorKaos64/SteamOS-Tools#100]
Hi,

Error in error binary package libattr1:i386 (installing skype)

I remove 2 two files in the package (in /usr/share/doc/libattr1/)
and manually install this custom package (i create it myself
without the 2 files)

Guy

$ aptitude reinstall libattr1:i386
The following packages will be REINSTALLED:
  libattr1 libattr1:i386 
0 packages upgraded, 0 newly installed, 2 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/36.9 kB of archives. After unpacking 0 B will be used.
(Reading database ... 128359 files and directories currently installed.)
Preparing to unpack .../libattr1_1%3a2.4.47-2+bsos3_amd64.deb ...
Unpacking libattr1:amd64 (1:2.4.47-2+bsos3) over (1:2.4.47-2+bsos3) ...
Preparing to unpack .../libattr1_1%3a2.4.47-2+bsos3_i386.deb ...
Unpacking libattr1:i386 (1:2.4.47-2+bsos3) over (1:2.4.47-2+bsos3) ...
dpkg: error processing archive /var/cache/apt/archives/libattr1_1%3a2.4.47-2+bsos3_i386.deb (--unpack):
 trying to overwrite shared '/usr/share/doc/libattr1/changelog.Debian.gz', which is different from other instances of package libattr1:i386
Errors were encountered while processing:
 /var/cache/apt/archives/libattr1_1%3a2.4.47-2+bsos3_i386.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
Failed to perform requested operation on package.  Trying to recover:
Setting up libattr1:amd64 (1:2.4.47-2+bsos3) ...
Processing triggers for libc-bin (2.19-18+steamos1+bsos1) ..

$ dpkg -i libattr1_1%3a2.4.47-2+bsos3_i386-custom.deb
(Reading database ... 128359 files and directories currently installed.)
Preparing to unpack libattr1_1%3a2.4.47-2+bsos3_i386-custom.deb ...
Unpacking libattr1:i386 (1:2.4.47-2+bsos3) over (1:2.4.47-2+bsos3) ...
Setting up libattr1:i386 (1:2.4.47-2+bsos3) ...
Processing triggers for libc-bin (2.19-18+steamos1+bsos1) ...
$

**Comment by ProfessorKaos64** [comment]
See this [FAQ](https://github.com/ProfessorKaos64/SteamOS-Tools/wiki/FAQ#i-cant-install-playonlinux-after-adding-the-extra-repositories) entry, and the one beneath it.

**Comment by guyr34** [comment]
Thank you ...
