### ISSUE TITLE
webapps do not open in full screen

### ISSUE THREAD

**Issue by dmbreton** [ProfessorKaos64/SteamOS-Tools#101]
It looks like there is an issue with the bash script pulling the xpdyinfo
Here is the terminal output when I manually run the script.
```
user@steamos:/usr/bin$ sudo ./Netflix-Launch.sh 
No protocol specified
xdpyinfo:  unable to open display ":0".
xprop: error: Invalid window id format: -f.
antimicro: error while loading shared libraries: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
```
_Note:_ I tried with sudo also and got the same result

This is the content of the Netflix-Launch.sh
```
  GNU nano 2.2.6          File: Netflix-Launch.sh                            

#!/bin/sh

WIN_RES=$(DISPLAY=:0 xdpyinfo | grep dimensions | awk '{print $2}')
COMMA_WIN_RES=$(echo $WIN_RES | awk '{sub(/x/, ","); print}')

/usr/bin/Xephyr :15 -ac -screen $WIN_RES -fullscreen -host-cursor -once & XE$

# For some reason, the Xephyr window never gets populated with a value for t$
# STEAM_GAME atom. It is possible to set the property manually though
sleep 1s
WINDOW_ID=$(xwininfo -root -children | grep "Xephyr" | awk '{print $4}')
xprop -id $WINDOW_ID -f "STEAM_GAME" 32c -set "STEAM_GAME" 8000

# start antimicro mouse control
antimicro --hidden --no-tray --profile /home/steam/antimicro/x360-wireless-m$

export DISPLAY=:15
LD_PRELOAD= google-chrome-stable --kiosk www.netflix.com --window-size=$COMM$

sleep 1

^G Get Help ^O WriteOut ^R Read File^Y Prev Page^K Cut Text ^C Cur Pos
^X Exit     ^J Justify  ^W Where Is ^V Next Page^U UnCut Tex^T To Spell

```

**Comment by ProfessorKaos64** [comment]
Please format your code with there back ticks (above TAB on English keyboard). I just tested this last night, when did you run this? Display 0 is fine. That is the display it should be running off of in the SteamOS BPM default session. You should not be running this from desktop mode. The missing libSDL2-2.0.so.0 library was included in the updated Antimicro package I just built yesterday. Please try the following:

```
sudo apt-get update
cd SteamOS-Tools
./desktop-software.sh install webapp
```

Try loading Netflix again.

**Comment by ProfessorKaos64** [comment]
For reference, it is [this](https://github.com/ProfessorKaos64/SteamOS-Tools-Packaging/blob/brewmaster/antimicro/debian/control#L20) line of the control file.

**Comment by dmbreton** [comment]
I tried updating and got the same result.  It looks like the lib is still missing

After an apt-get update have this

```
desktop@steamos:/usr/bin$ sudo apt-cache show antimicro
Package: antimicro
Installed-Size: 3644
Maintainer: ProfessorKaos64
Architecture: amd64
Version: 20151006+git-1
Provides: antimicro
Replaces: antimicro
Priority: extra
Section: X11
Filename: pool/main/a/antimicro/antimicro_20151006+git-1_amd64.deb
Size: 787604
SHA256: 1982118aa3c2f28af7382762127bdb601d8012e102538ad90661e6827d92794d
SHA1: cb1f0dc18b5842e911ba0383bfc3499899c009a1
MD5sum: 769132ebac24138b422fdea5fe6cd6ee
Description: Antimicro build for SteamOS
Description-md5: 4711e5d2ec1a4108071e2c80f7be078f
```

**Comment by ProfessorKaos64** [comment]
Yep, that's the old package it's pulling. I will be able to remove that in about 2 hours or so. If you wish to update it now, I think the following may work, otherwise, just give me a few hours.
```
cd
wget http://packages.libregeek.org/SteamOS-Tools/pool/main/a/antimicro/antimicro_2.20.2+git+bsos1_all.deb
sudo gdebi antimicro_2.20.2+git+bsos1_all.deb
```

**Comment by dmbreton** [comment]
I will wait until you make the update and give it a shot.  Let me know when.

**Comment by ProfessorKaos64** [comment]
Ok, there should only be `antimicro_2.20.2+git+bsos1` in the package pool now. Try:
```
sudo apt-get update
sudo apt-get remove antimicro
sudo apt-get install antimicro
````

If it does not pull that version, remove it from `/var/cache/apt/archives/antimicro*`

**Comment by dmbreton** [comment]
Okay I have the right library now, bu the app fails to open in full screen(kiosk) mode.  I may try doing a clean install and trying again.

**Comment by ProfessorKaos64** [comment]
@dmbreton , any update?

**Comment by dmbreton** [comment]
I will give it a shot later today.  Got sidetracked on another project.

Dave

**Comment by ProfessorKaos64** [comment]
Ok, when you do, take note the window code is only really useful (for kiosk mode, resolution wrangling) when run in the intended SteamOS BPM session. In desktop mode, the window will appear small, and you will see errors in the terminal like the ones you saw in your original post.

**Comment by dmbreton** [comment]
you can close this one.  It is working as expected now.
