### ISSUE TITLE
PlexHomeTheater Errors on SteamOS Brewmaster

### ISSUE THREAD

**Issue by pogipants** [ProfessorKaos64/SteamOS-Tools#104]
Followed your guide, but i get an error about not being able to find XBMC files. Otherwise it might say segmentation fault.

---------------------
Admin edit (pk) - for users catching this thread, please reference the Wiki page:
https://github.com/ProfessorKaos64/SteamOS-Tools/wiki/OpenPHT

**Comment by ProfessorKaos64** [comment]
Which guide/ page? Should be a simple apt-get install, unless the information is old

**Comment by pogipants** [comment]
I followed this guide on Steam Community 
http://steamcommunity.com/sharedfiles/filedetails/?id=406566142

I just installed the newest version of SteamOS with brewmaster. On Oct 31st, on this guide page, you say this method is no longer up to date. 

It complains about missing XBMC files or a segmentation fault, depending on if I sudo plexhometheater or just ./plexhometheater

**Comment by ProfessorKaos64** [comment]
hmmmm, the simple apt-get install should be fine. Let me take a look from a fresh install.

**Comment by ProfessorKaos64** [comment]
There was a issue with the SKS keyserver pool not connecting to import the proper GPG key. Could you try the steps from that guide once more? Before doing so, remove the current plexhometheater with 'sudo apt-get purge plexhometheater'

**Comment by pogipants** [comment]
Hi Mikeyd,

I still get the error in /var/log/messages "steamos
plexhometheater.desktop[1599]: Segmentation  fault"

so weird, everything else works fine

**Comment by pogipants** [comment]
13 T:139766154655488    INFO: Network change for browser (polled=0),
closing 0 browse sockets.
17:02:13 T:139766154655488    INFO: NetworkService: Setting up multicast
listener on 0.0.0.0:32415 (outbound: 0)
17:02:13 T:139766154655488    INFO: NetworkService: Browsing on interface
127.0.0.1 on broadcast address 127.255.255.255 (index: 0)
17:02:13 T:139766154655488    INFO: NetworkService: Browsing on interface
192.168.0.106 on broadcast address 192.168.0.255 (index: 1)
17:02:13 T:139766154655488   DEBUG: CPlexServerManager::UpdateReachability
Updating reachability (force=YES)
17:02:13 T:139766154655488   DEBUG: CPlexMediaServerClient::publishDevice
Adding interface: http://192.168.0.106:3005/ for publishing
17:02:13 T:139766154655488   DEBUG: CPlexMediaServerClient::publishDevice
Going to call url:
https://plex.tv:443/devices/64074396-90d2-4d62-8b25-35ba86c730d7&Connection%5b%5d%5buri%5d=http%3a%2f%2f192.168.0.106%3a3005%2f
17:02:13 T:139766391514880   DEBUG: Loading: libcurl-gnutls.so.4.2.0
17:02:13 T:139766391514880   ERROR: Unable to load libcurl-gnutls.so.4.2.0,
reason: libcurl-gnutls.so.4.2.0: cannot open shared object file: No such
file or directory
17:02:13 T:139766391514880   DEBUG: Dll libcurl-gnutls.so.4.2.0 was not
found in path


Justin Michel
paypal.me/pogipants
about.me/justinmichel
*ihatemanuals.wordpress.com <http://ihatemanuals.wordpress.com>*
Ask me for the Discord Chat Server info

**Comment by ProfessorKaos64** [comment]
Ok, I'll repackage this and reassess. I'll give you a shout when I have a new package up.

**Comment by ProfessorKaos64** [comment]
Their upstream debian packaging form the PPA was a bit screwy. I did a few build attempts, but one of the makefiles was causing a failure, so I need to look into that when I have. However, I did checkout the debian source control file for the 15.04 Vivid build. That contains libcurl4-gnutls-dev, which [contains](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=contents&keywords=ibcurl-gnutls.so) libcurl-gnutls.so. I ran into the same* makefule error. I'll see what else I can do.

```
xbmc/CMakeFiles/xbmc.dir/build.make:13121: recipe for target 'xbmc/CMakeFiles/xbmc.dir/peripherals/devices/PeripheralCecAdapter.cpp.o' failed
make[3]: *** [xbmc/CMakeFiles/xbmc.dir/peripherals/devices/PeripheralCecAdapter.cpp.o] Error 1
make[3]: Leaving directory '/home/desktop/build-deb-temp/plexhometheater-1.4.1.469-201505131108/obj-x86_64-linux-gnu'
CMakeFiles/Makefile2:1122: recipe for target 'xbmc/CMakeFiles/xbmc.dir/all' failed
make[2]: *** [xbmc/CMakeFiles/xbmc.dir/all] Error 2
make[2]: Leaving directory '/home/desktop/build-deb-temp/plexhometheater-1.4.1.469-201505131108/obj-x86_64-linux-gnu'
Makefile:140: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/desktop/build-deb-temp/plexhometheater-1.4.1.469-201505131108/obj-x86_64-linux-gnu'
/usr/share/cdbs/1/class/makefile.mk:47: recipe for target 'debian/stamp-makefile-build' failed
make: *** [debian/stamp-makefile-build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
Build command 'cd plexhometheater-1.4.1.469-201505131108 && dpkg-buildpackage -b -uc' failed.
E: Child process failed
```

**Comment by ProfessorKaos64** [comment]
I found a [fork](https://github.com/RasPlex/OpenPHT/issues/10) which seems to continue development. I wonder if they could help with resolving the debian build errors. I'll keep working at it, as it will be some time until Plex Media Player is sorted out. PMP requires very* new qt, cmake, and mpv packages. 

@sharkwouter @directhex, any ideas on the build errors above this post?

- [debian set](https://github.com/ProfessorKaos64/SteamOS-Tools-Packaging/tree/brewmaster/plexhometheater)
- [build script](https://github.com/ProfessorKaos64/SteamOS-Tools-Packaging/blob/brewmaster/build-plexhometheater.sh)

**Comment by directhex** [comment]
You've cut off the build log too early, I need another few dozen lines of context

**Comment by ProfessorKaos64** [comment]
Actually I might have it, I made it to the very end of the package attempt, only to realize this time, that plexhometheater.install have a few files installing from debian/, when I had moved them to the main source tree (.desktop file, main script, steam banner). I think the Open-PHT fork may work here.

**Comment by ProfessorKaos64** [comment]
@directhex , here is the full log. Still working at it tonight, so things may change:
https://gist.github.com/ProfessorKaos64/b9ccba7b0b13e1e4f7c2

Seems to be something screwy with the cec version.

**Comment by ProfessorKaos64** [comment]
Thanks to some [patch sets](http://www.preining.info/debian/pool/pht/p/plexhometheater/) I was able to overcome the cec issue. Only thing left (I hope) is to correct the library path in the rules file, since this package is so screwy. From what I read, is a bad practice, but it is how it is at the moment.

**Comment by ProfessorKaos64** [comment]
See the below reddit post for full information. Deb has build built to the [libregeek repository](http://packages.libregeek.org/SteamOS-Tools/pool/main/o/openpht/) under brewmaster_testing.

**Comment by pogipants** [comment]
Hi mikeyd,

That deb file seemed to do the trick. The only thing I noticed is that when launching PHT from Steam Big Picture mode that when the controller goes to sleep, it will not interact with PHT, but only Steam. Great work though, i'm so thankful for the effort, you saved SteamOS for me.

**Comment by ProfessorKaos64** [comment]
That issue is known, even with older versions. Maybe OpenPHT will eventually fix that, or a talented dev will help. Thank you for testing this initial version. 

On December 8, 2015 11:12:02 AM EST, pogipants <notifications@github.com> wrote:
>Hi mikeyd,
>
>That deb file seemed to do the trick. The only thing I noticed is that
>when launching PHT from Steam Big Picture mode that when the controller
>goes to sleep, it will not interact with PHT, but only Steam. Great
>work though, i'm so thankful for the effort, you saved SteamOS for me. 
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ProfessorKaos64/SteamOS-Tools/issues/104#issuecomment-162931649

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ProfessorKaos64** [comment]
Update: openpht (20151207+git+bsos-1) is now in brewmaster, the typical repo. Run `sudo apt-get update` and then `sudo apt-get intstall openpht`

**Comment by ProfessorKaos64** [comment]
@pogipants , if this build works, can you please close? Thank you.

**Comment by pogipants** [comment]
New build works! Closing issue.
