### ISSUE TITLE
Steam game running through wine crashes in BPM, but loads in the desktop

### ISSUE THREAD

**Issue by BJSerpas** [ProfessorKaos64/SteamOS-Tools#115]
So I've already set up a number of Steam games using this guide:

https://github.com/ProfessorKaos64/SteamOS-Tools/wiki/Playing-Steam-%28Windows%29-Games-Using-PlayOnLinux

And those games have run 100% perfectly fine without issues. But now I'm trying to play Sonic Adventure 2 (App ID 213610), and it just won't work in BPM whatsoever. When I try to launch it using the normal method, the Wine virtual desktop loads, but then a generic error message pops up, something like "Launcher.exe has encountered a problem and needs to close," and I'm asked to send an error report to Microsoft. After hitting "Don't Send," another error window pops up: "Program Error: The program Launcher.exe has encountered a serious problem and needs to close."

So to make a long story short, the game catastrophically crashes in BPM if I try to load it. But if I go to desktop mode, load up PlayOnLinux (through the steam user, thanks to the handy shortcut), launch Steam, and then launch the game like that, it works great - no issues. It's really odd that other games have worked for me, but this one doesn't, on top of the fact that it works in desktop mode but not BPM.

I don't think this could be a permissions error preventing wine from reading some libraries the game needs, because when I launch it through desktop mode, I'm launching it through the 'steam' user.

I tried making a script to load the game executable directly with wine (and CrossOver's version of wine, I tried both), but I get the same error in BPM. I tried this with other indie game .exe's I have and they load right up in BPM.

I also tried creating a script with the command "playonlinux --run "Steam" -applaunch 213610," and that will work in desktop mode if I su into the 'steam' user, but if I try launching that script in BPM, it actually crashes completely and BPM loads up again.

I feel like I've tried everything. Is there a possible solution for this?

**Comment by ProfessorKaos64** [comment]
I'll try to see what I can do. Bear in mind not all games will work great via Wine, and furthermore, like you see, can fight SteamOS BPM. Can you link pastebins or GitHub Gists of the files you made? I may own that game to test.

**Comment by BJSerpas** [comment]
Sure. Here's the file in /usr/bin (named sonicadv2): http://pastebin.com/mcD6LVPK
And here's the .desktop file: http://pastebin.com/LSC7R2nJ

Let me know if you need anything else.

**Comment by ProfessorKaos64** [comment]
Thanks, I'll test this tonight. On first glance, the launcher's line 23 has a quit on its own line. Back that up to be on the end of the game dir. The var isn't used though.

On January 8, 2016 11:18:18 AM EST, BJSerpas <notifications@github.com> wrote:
>Sure. Here's the file in /usr/bin (named sonicadv2):
>http://pastebin.com/mcD6LVPK
>And here's the .desktop file: http://pastebin.com/LSC7R2nJ
>
>Let me know if you need anything else.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ProfessorKaos64/SteamOS-Tools/issues/115#issuecomment-170044852

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Ryochan7** [comment]
One thing that I notice is that you are watching for the wrong exe. It looks like GAME_EXE should be sonic2app.exe and not Launcher.exe. Since Launcher.exe quits when sonic2app.exe gets launched, the script will attempt to kill Steam.exe and the Wine server around the same time the game is launching. That would cause some major problems.

I have the Windows version of Sonic Adventure 2 in my Steam library. I will check this out in Wine later.

**Comment by ProfessorKaos64** [comment]
@Ryochan7 , thanks for the assist. Appreciate it Sir.

**Comment by Ryochan7** [comment]
I found the problem and now Sonic Adventure 2 works fine when launched directly in SteamOS BPM. It was a matter of changing LD_LIBRARY_PATH to include the lib directories for the version of wine that you are running. Something like this should probably be added to the base script.

    export LD_LIBRARY_PATH="$WINEVERSION/lib:$WINEVERSION/lib64:$LD_LIBRARY_PATH"

Also, I am not sure why but the exe to watch for is **sonic2App.exe** (note the uppercase A). The actual filename is all lowercase but it shows up in htop and pgrep with the letter A.

**Comment by ProfessorKaos64** [comment]
@Ryochan7 , do you mind linking a paste of the completed launcher? I want to start storing community made launchers for reference.

**Comment by Ryochan7** [comment]
Here is a copy of the script. https://gist.github.com/Ryochan7/17cdb0c4d24db804dfd3

**Comment by ProfessorKaos64** [comment]
Is the LD export needed for the Skelton file or just that game?

On January 8, 2016 8:33:40 PM EST, Travis Nickles <notifications@github.com> wrote:
>Here is a copy of the script.
>https://gist.github.com/Ryochan7/17cdb0c4d24db804dfd3
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ProfessorKaos64/SteamOS-Tools/issues/115#issuecomment-170176463

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Ryochan7** [comment]
So far, I have only needed it for this game. PlayOnLinux sets LD_LIBRARY_PATH in that fashion when it launches an installed application and that was the main reason that Sonic Adventure 2 worked fine when launched from PlayOnLinux but not from the script. I think it might be a good idea to have something similar included in the Skelton file.

**Comment by ProfessorKaos64** [comment]
I will add that line and comment this original for good keeping. 

On January 8, 2016 8:39:23 PM EST, Travis Nickles <notifications@github.com> wrote:
>So far, I have only needed it for this game. PlayOnLinux sets
>LD_LIBRARY_PATH in that fashion when it launches an installed
>application and that was the main reason that Sonic Adventure 2 worked
>fine when launched from PlayOnLinux but not from the script. I think it
>might be a good idea to have something similar included in the Skelton
>file.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ProfessorKaos64/SteamOS-Tools/issues/115#issuecomment-170176865

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by BJSerpas** [comment]
Thanks guys! The new script works great. I'd hate to be picky, but while I have you guys, rather than submit a new issue, it it possible to fix the mouse cursor in the virtual wine desktop while in BPM? For whatever reason, the cursor seems to avoid windows like the plague. You have to do a lot of clicking and holding and dragging just to interact with windows. I'm sure you already know about this issue, but do you have any workarounds or pointers?

**Comment by ProfessorKaos64** [comment]
Thank you @Ryochan7 , added. Noted and commented. Added your launcher to new DIR launchers/wine-pol-launchers with you as credited. 

@BJSerpas , this particular issue is closed. Could you please submit a new issue if you have further trouble? I'm not sure what can be done about the mouse. This methods implemented with POL are meant to only show the virtual desktop briefly, maybe in the future, not at all (seemingly). The virtual desktop is not meant to be interacted with (at least not at this time).

Updated:
* [wiki](https://github.com/ProfessorKaos64/SteamOS-Tools/wiki/Playing-Steam-%28Windows%29-Games-Using-PlayOnLinux)
* [launcher skel](https://github.com/ProfessorKaos64/SteamOS-Tools/blob/brewmaster/cfgs/wine/pol-game-launcher.skel)
* [added SonicAdventure2 launcher](https://github.com/ProfessorKaos64/SteamOS-Tools/blob/brewmaster/launchers/wine-pol-launchers/SonicAdventure2)
