### ISSUE TITLE
Fix Ice install for SteamOS

### ISSUE THREAD

**Issue by ProfessorKaos64** [ProfessorKaos64/SteamOS-Tools#116]
Work in progress issues stub.

See: https://github.com/ProfessorKaos64/Ice/

**Note**

This is now uploaded to the repository as "ice-steamos", which is subject to change / deletion as upstream matures.

**Comment by dmbreton** [comment]
My XBox 360 wireless controller is not working out of the box.  It seems like this should be autconfigured by retroarch, am I mistaken?

**Comment by ProfessorKaos64** [comment]
It should since retroarch-joypad-autoconfig is installed along side. What game, system did you try?

**Comment by dmbreton** [comment]
I tried NES (Super Mario Brothers 3).  I have tried with both the Steam controller and the wireless Xbox 360 controller.  Are there any logs/configs that would be useful to troubleshoot?

**Comment by ProfessorKaos64** [comment]
And you're using the default "ice-steamos" package? What do your emulators.txt and consoles.txt look like for that particular entry? If unmodified, it would be using RetroArch's fceumm core. I usually test Super Mario Bros., and have done so with both of those controllers. I'll take a look tonight again as well.

**Comment by dmbreton** [comment]
Yes I am using the ice-steamos package with the default configs.  Let me know where the logs are and I can take a look.  I am not familiar with retroarch and where is stores the logs and configs

**Comment by ProfessorKaos64** [comment]
attach pastebin / GIst links to:

/etc/ice/consoles.txt
/etc/ice/emulators.txt

Do you see this as well?

```
desktop@steamos:~$ apt-cache policy retroarch retroarch-joypad-autoconfig
retroarch:
  Installed: 1.3.1+git+bsos1
  Candidate: 1.3.1+git+bsos1
  Version table:
 *** 1.3.1+git+bsos1 0
        150 http://packages.libregeek.org/SteamOS-Tools/ brewmaster/main amd64 Packages
        100 /var/lib/dpkg/status
retroarch-joypad-autoconfig:
  Installed: 0.1+git+bsos3
  Candidate: 0.1+git+bsos3
  Version table:
 *** 0.1+git+bsos3 0
        150 http://packages.libregeek.org/SteamOS-Tools/ brewmaster/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by dmbreton** [comment]
See below

[emulators.txt](http://pastebin.com/a6Vw00wT)
[consoles.txt](http://pastebin.com/6V56NxBY)

''''
desktop@steamos:/etc/ice$ apt-cache policy retroarch retroarch-joypad-autoconfig
retroarch:
  Installed: 1.3.1+git+bsos1
  Candidate: 1.3.1+git+bsos1
  Version table:
 *** 1.3.1+git+bsos1 0
        500 http://packages.libregeek.org/SteamOS-Tools/ brewmaster/main amd64 Packages
        100 /var/lib/dpkg/status
retroarch-joypad-autoconfig:
  Installed: 0.1+git+bsos3
  Candidate: 0.1+git+bsos3
  Version table:
 *** 0.1+git+bsos3 0
        500 http://packages.libregeek.org/SteamOS-Tools/ brewmaster/main amd64 Packages
        100 /var/lib/dpkg/status

''''

**Comment by ProfessorKaos64** [comment]
@dmbreton version 1.0.0 was released upstream. Testing this today. When complete, i'll have you update and retest your issue. I debianized the python package dependencies to make this happen.

**Comment by dmbreton** [comment]
Had an issue with diskspace and needed to re-build my machine.  I have a fresh install. I am getting similar results.

Which settings menu are you referring to for the controller? 

```
desktop@steamos:~$ apt-cache policy retroarch retroarch-joypad-autoconfig
retroarch:
  Installed: 1.3.1+git+bsos1
  Candidate: 1.3.1+git+bsos1
  Version table:
 *** 1.3.1+git+bsos1 0
        150 http://packages.libregeek.org/SteamOS-Tools/ brewmaster/main amd64 Packages
        100 /var/lib/dpkg/status
retroarch-joypad-autoconfig:
  Installed: 0.1+git+bsos3
  Candidate: 0.1+git+bsos3
  Version table:
 *** 0.1+git+bsos3 0
        150 http://packages.libregeek.org/SteamOS-Tools/ brewmaster/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by ProfessorKaos64** [comment]
Settings menu of Retroarch itself, which runs underneath to use the cores (for each emulator). If you switch to the Steam user in desktop mode (su - steam) and launch Retroarch, you should be able to check out the settings in the full Retroarch menu. Do _none_ of the buttons on your gamepad work, or Just some? This is tricky for me, since I always test Mario Bros. (NES) on a new build. I use Steam Controllers, official Microsoft Xbox 360 controllers (wired/wireless) and PS3/PS4 controllers for testing.

**Comment by dmbreton** [comment]
Hmm I only see retroarch when logged in as the "desktop" user.  I wonder if everything from ice-steamos is installing correctly

**Comment by ProfessorKaos64** [comment]
You may need to edit the desktop file under "/usr/share/applications/" for Retroarch. It may not show up in BPM due to a space in the Exec line or validation error. Use the below text to replace it.

```
[Desktop Entry]
Version=1.0
Name=Retroarch
GenericName=Retroarch
Comment=Retroarch client
Exec=retroarch
Icon=retroarch
Terminal=false
Type=Application
Categories=Game
Actions=Fullscreen;Standalone;
```

But...it should really be there under your "Add Library shortcut." If it is not, is it in your installed applications list? You can get around this in desktop mode, but switching to the steam user with `su - steam` after setting the password with `sudo passwd steam`. Then launch retroarch in the terminal window with `retroarch`.

**Comment by dmbreton** [comment]
I'll take a look again later tonight.  Thanks for the help

**Comment by ProfessorKaos64** [comment]
NP, hopefully I can help. Also, make sure your ice-steamos install version is the last per [this folders](http://packages.libregeek.org/SteamOS-Tools/pool/games/i/ice-steamos/) noted version. If it isn't, perform `sudo apt-get install ice-steamos`. 

If you previously had the 0.1.0 release installed, and have a dpkg error with "sudo apt-get update ice-steamos", perform the following:

```
    sudo apt-get install -f
    sudo dpkg -i --force-overwrite /var/cache/apt/archives/ice-steamos_VERSION_all.deb
```

*Replace VERSION with whatever the latest package version/revision is* (Packaging and more so, python packaging,has been a learning process). list the contents of the downloaded archives with 'ls /var/cache/apt/archives/ | grep ice*'

**Comment by dmbreton** [comment]
I am on the latest version and it seem like the controllers are not auto-configured.  "retroarch-joypad-autoconfig" is installed, but the wireless xbox 360 controller I have tried does not seem to work.

I did confirm that i am on the latest ice-steamos

**Comment by ProfessorKaos64** [comment]
Check here, under the gamepad you have:
https://github.com/libretro/retroarch-joypad-autoconfig/tree/master/udev

I could be that the [vendor id](https://github.com/libretro/retroarch-joypad-autoconfig/issues/38) is off as well for the receiver (if it's Microsoft brand). You can check this with `lsusb -v | less` under the attached devices for Microsoft / Xbox360. I can tell you that this is not an issue with ice-steamos. I have installed it a few times from scratch and have official Xbox 360 wireless and wired pads. The joypad controls are pushed as udev rules per that linked repo. Check your device information and also possibly check with the upstream devs there why it isn't recognized. 

Start by launching Retroarch in desktop mode and testing from there just by opening up RetroArch and toying around.

**Comment by dmbreton** [comment]
Think you are correct.  It very much looks like an issue with libretro

Should this file "Xbox_360_Wireless_Receiver.cfg" be in the "SteamOS-Tools/cfgs/retroarch"  folder?

I cannot find this anywhere on my system.

**Comment by dmbreton** [comment]
I may give up on this one.  It's not working for either the wireless xbox 360 controller or the steam controller.  

It looks like the cfgs are in the libretro folder but I can not figure out why the controllers are not being configured

**Comment by dmbreton** [comment]
Could this be the issue?  Look like the steam user could not have the correct permissions to us the /dev/input devices.  

https://github.com/libretro/RetroArch/wiki/Input-drivers-in-Linux-without-Xorg

By default in most distros, /dev/input nodes are root-only (mode 600).

```
desktop@steamos:/dev/input$ ls -l
total 0
drwxr-xr-x  2 root root     160 Feb  8 09:43 by-id
drwxr-xr-x  2 root root     180 Feb  8 09:43 by-path
crw-rw----  1 root input 13, 64 Feb  8 09:42 event0
crw-rw----  1 root input 13, 65 Feb  8 09:42 event1
crw-rw----  1 root input 13, 74 Feb  8 09:42 event10
crw-rw----  1 root input 13, 75 Feb  8 09:42 event11
crw-rw----+ 1 root input 13, 76 Feb  8 09:43 event12
crw-rw----  1 root input 13, 66 Feb  8 09:42 event2
crw-rw----  1 root input 13, 67 Feb  8 09:42 event3
crw-rw----  1 root input 13, 68 Feb  8 09:42 event4
crw-rw----  1 root input 13, 69 Feb  8 09:42 event5
crw-rw----  1 root input 13, 70 Feb  8 09:42 event6
crw-rw----  1 root input 13, 71 Feb  8 09:42 event7
crw-rw----  1 root input 13, 72 Feb  8 09:42 event8
crw-rw----  1 root input 13, 73 Feb  8 09:42 event9
crw-rw-r--+ 1 root input 13,  0 Feb  8 09:43 js0
crw-rw----  1 root input 13, 63 Feb  8 09:42 mice
crw-rw----  1 root input 13, 32 Feb  8 09:42 mouse0
crw-rw----  1 root input 13, 33 Feb  8 09:42 mouse1
```

```
desktop@steamos:/dev/input$ cat /etc/group | grep input
input:x:101:
```

**Comment by ProfessorKaos64** [comment]
That is how both my main and test SteamOS boxes are as well. Even if so, both of mine work, and this would be an upstream issue with SteamOS itself. If it were though, I could patch things, but I am wary of messing with input rules and system files in this way. The steamcompmgr compository still uses Xorg...

> SteamOS is based on Debian Linux, with the standard X Window System on top of it. There are a number of customizations, as well as the SteamOS compositing manager (steamcompmgr). There is also "a long list of kluges" that make X work for SteamOS, he said.

>Steam and SteamOS use essentially the same software, but provide a different experience for users, which embodies the difference between the desktop and console worlds. On the desktop, there may be many applications running on multiple monitors, with desktop widgets, icons, menus, and so forth. On a console, there is just one full-screen application. Any system UI in a console is either an overlay, as in Steam, or simply replaces the game entirely.

[Source](https://lwn.net/Articles/611969/)

I'll test once more tonight, but if you adamant about getting this working, I would try a reinstall of SteamOS. That's up to you. I'll let you know how I make out and my steps to reproduce.

**Comment by dmbreton** [comment]
Retro-Arch does not detect the gamepad when when running in desktop mode, even when launching as the steam user.  I can see in the logs that it sets up a "Retropad"  controller.  I will post the logs here  later

**Comment by ProfessorKaos64** [comment]
I also now get

```
"Xbox 360 Wireless Receiver (1118/1817) not configured"
```

This used to work just fine. I'll see what I can do.

**Comment by ProfessorKaos64** [comment]
Should work now:

```
desktop@steamos:~/SteamOS-Tools-Packaging/retroarch/retroarch$ apt-cache policy retroarch
retroarch:
  Installed: 1.3.1+git+bsos2
  Candidate: 1.3.1+git+bsos2
  Version table:
 *** 1.3.1+git+bsos2 0
        150 http://packages.libregeek.org/SteamOS-Tools/ brewmaster/main amd64 Packages
        100 /var/lib/dpkg/status

```

**Comment by dmbreton** [comment]
Hmm not working...

I am not sure that I did not mess something up when I was troubleshooting. 

```
desktop@steamos:~$ apt-cache policy retroarch
retroarch:
  Installed: 1.3.1+git+bsos2
  Candidate: 1.3.1+git+bsos2
  Version table:
 *** 1.3.1+git+bsos2 0
        150 http://packages.libregeek.org/SteamOS-Tools/ brewmaster/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by ProfessorKaos64** [comment]
Not sure. I'll do a system restore and test again tonight. You configuration files may be old. I would try purging `retroarch` and trying again

Removing retroarch does not seem to remove the configuration file I believe, so do:

```
sudo rm -f /home/steam/.config/retroarch
```

Purge and reinstall
```
sudo apt-get purge retroarch*
sudo apt-get install ice-steamos
```

**Comment by ProfessorKaos64** [comment]
I believe my dpad / joystick didn't work possibly on the main menu of Super Mario Bros., but I hit start and it worked after the game began. I'll check again tonight from a fresh install of SteamOS.

**Comment by dmbreton** [comment]
Purged seems to have fixed it.  I only tried one game.  Will do a few more tests later tonight.

**Comment by ProfessorKaos64** [comment]
Thank you for your patience while I sorted this out. Let me know. i'll try to find time to test as noted above. I'll see if I can help that config file sticking behind.

**Comment by ProfessorKaos64** [comment]
I was testing this today, all seemed well from me. @dmbreton , anything else to report? If not, i'll consider this closed.

**Comment by dmbreton** [comment]
You can close this.  Its working well for me now.  I tried on a few different emulators (NES, SNES, PSX).

Thanks for the help
