### ISSUE TITLE
Installing and activating PVR addon tvheadend-hts crashes Kodi

### ISSUE THREAD

**Issue by Juppstein** [ProfessorKaos64/SteamOS-Tools#117]
Latest Kodi on SteamOS 2.59 with SteamOS-Tools repo, after getting an update to tvheadend-hts addon, Kodi will no longer start up and will crash/close about 1-2 seconds after starting it.

Here is a snip from the crash log
```
10:49:36 T:139827994667072 WARNING: JSONRPC: Could not parse type "PVR.Details.Channel"
10:49:36 T:139827994667072 WARNING: JSONRPC: Could not parse type "PVR.Details.ChannelGroup.Extended"
10:49:36 T:139827994667072 WARNING: JSONRPC: Could not parse type "GUI.Property.Value"
10:49:36 T:139827994667072 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
```
more of the log can be found here: 
http://steamcommunity.com/groups/steamuniverse/discussions/1/523898291499139752/#c458605613400460828

kodi-pvr-tvheadend version:

```
Package: kodi-pvr-tvheadend-hts
Versions:
2.2.10+git+bsos1 (/var/lib/apt/lists/packages.libregeek.org_SteamOS-Tools_dists_brewmaster_main_binary-amd64_Packages) (/var/lib/dpkg/status)
 Description Language:
                 File: /var/lib/apt/lists/packages.libregeek.org_SteamOS-Tools_dists_brewmaster_main_binary-amd64_Packages
                  MD5: 7d33c28479a1895474cae38e5513d971
```

Kodi version:
```
Package: kodi
Versions:
15.2+dfsg1-1~bpo8+1 (/var/lib/apt/lists/httpredir.debian.org_debian_dists_jessie-backports_main_binary-amd64_Packages)

```

**Comment by ProfessorKaos64** [comment]
I'll rebuild with the legacy platform package tomorrow.  That's likely the issue.

**Comment by ProfessorKaos64** [comment]
I got some of the pre-requisite packages rebuilt, but having trouble with Kodi's build. Looking at this more tonight.

**Comment by ProfessorKaos64** [comment]
Not sure why I am having trouble rebuilding 15.2 Isengard all of a sudden. I will try again tonight if I can, or later this week. Jarvis is soon on the horizon, so if this continues, rebuilding all Kodi packages will just have to wait until Jarvis is out the door upstream.

**Comment by Juppstein** [comment]
but shouldn't your Kodi version be pulled automatically when doing an apt-get install kodi? You are right, this is the debian version, I just wonder why that got installed even though have your repo active.

**Comment by ProfessorKaos64** [comment]
Hmm, I'm not sure. It should be yes, as the version number should supercede what is in debian's (of which they uploaded anyway). You could try to download the pvr deb from the pool below, after installing Kodi from my repo. I'll try to solve this tonight if I can find time.

http://packages.libregeek.org/SteamOS-Tools/pool/main/k/

Kodi is there, as well as the pvr addons. I'll keep working on fixing the current release until Jarvis is officially out.

**Comment by Juppstein** [comment]
Yep, I'll try that. It's not biggie because I can use the TVHeadend app on my Android tablet to then send the channel stream back to Kodi on my TV via Yatse :) There's always a way.

**Comment by Juppstein** [comment]
Purged the Kodi installation and reinstalled it again, this time it looks like it has the libregeek one installed. Though the problem persist and Kodi crashes with activated tvh-hts addin.

**Comment by ProfessorKaos64** [comment]
Strange. Thank you for your patience in this. This is a tough one. Do I
spend time trying to really get 15.2 isengard fixed up (for the builds) or
just wait the short time for the Jarvis release? Additionally, in due time,
the Kodi pakages will be in Jessie-backports. The main packages are there,
but only 1 or 2 pvr addons.

On Thu, Jan 14, 2016 at 12:55 PM, Juppstein <notifications@github.com>
wrote:

> Purged the Kodi installation and reinstalled it again, this time it looks
> like it has the libregeek one installed. Though the problem persist and
> Kodi crashes with activated tvh-hts addin.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ProfessorKaos64/SteamOS-Tools/issues/117#issuecomment-171722327>
> .
>



-- 
Michael DeGuzis
Email: mdeguzis@gmail.com
Website: http://www.libregeek.org
Linked In Resume/Profile
<http://www.linkedin.com/profile/view?id=124915388&trk=nav_responsive_tab_profile>

**Comment by Juppstein** [comment]
Dunno, if we talk about 2 weeks or so it would be worth ignoring me and my issue and wait for Jarvis :)

**Comment by ProfessorKaos64** [comment]
I want to focus on making sure my builds follow Jarvis, which I need to work on, that would be preferred. Maybe eventually all packages will be in jessie-backports and I will have to do 0 work haha.

**Comment by Juppstein** [comment]
Just wanted to let you know that after the latest update of the pvr-tvheaded plugin it works again. So whatever you did, it worked :)

**Comment by ProfessorKaos64** [comment]
Hazah! I think this was on another thread and I forgot to also comment here. Yes, everything was built against Isengard, as some were off the master branch. See #123 . Thank you Juppestein for the feedback.
