### ISSUE TITLE
POL-Script doesn't open game in BPM. On desktop it works

### ISSUE THREAD

**Issue by silelmot** [ProfessorKaos64/SteamOS-Tools#120]
Hello
I installed the script and desktop file some days ago and cant get it to work properly. 
On desktop it runs great (after i changedt the "grep "Friends"  to my language)  but in steamos BPM it wont start. Tried it without translating the line also. 
I tried it with the games Nidhogg and Deadpool. 

edit: sorry, there was a wrong spelling-correction by my smartphone.

**Comment by ProfessorKaos64** [comment]
Attache your launcher files in a Gist or Pastebin.

**Comment by silelmot** [comment]
Ok, here is the one for deadpool:

<script src="https://gist.github.com/silelmot/880f4ba6db2eb0933a34.js"></script>

**Comment by ProfessorKaos64** [comment]
I do own this game. I'll take a look tonight.

**Comment by silelmot** [comment]
thats great. thank you much!

**Comment by ProfessorKaos64** [comment]
If I can figure it out, I will store it here:
https://github.com/ProfessorKaos64/SteamOS-Tools/tree/brewmaster/launchers/wine-pol-launchers

**Comment by ProfessorKaos64** [comment]
Actually I do not  have Deadpool, I thought I did. I the only think I can tell you is:

* I wouldn't comment line 25 from your paste, unless you have to. 
* Ensure `/home/steam/.PlayOnLinux/wine/linux-x86` contains 1.9.1
* Ensure Steam in PlayOnLinux is configured to use 1.9.1. 
* Try a different version of Wine to use on Steam, such as 1.8
* Run the game windowed or ALT+TAB out of it from the SteamOS Desktop mode. Check the output of htop and pgrep while the game is running. Make sure the .exe name matches what you saw. [Similar issue](https://github.com/ProfessorKaos64/SteamOS-Tools/issues/115). You will have to install htop. The game exe may be "dp.exe" not "DP.exe". Capitalization matters in Linux-based systems.

@Ryochan7 , any ideas on [Deadpool](https://steamdb.info/app/224060/config/)?

**Comment by silelmot** [comment]
thanks. i will try all your suggestions tomorrow. although i am sure that the first 3 are right with my settings. and DP.exe may be wrong but shouldnt affect the starting of the game, but the shutting down. but i will look over this too

**Comment by Ryochan7** [comment]
Have you tried launching the game using PlayOnLinux and then running a system monitor, such as htop, to see how the game is launched? As was discovered in issue #115 regarding Sonic Adventure 2, launching a game under Wine might actually make the executable appear with a slightly different case filename than what is actually stored on the file system. DP.exe might not be the proper entry for GAME_EXE.

**Comment by silelmot** [comment]
OK.first, as i understand the script, the exe of the game is only important for the shutdown-process. But nethereless its the right one. Also i tried this with nidhogg and the" poket at the assembly" and its always the same. I tried wine 1.8 also.nothing. but i read an error in the syslog for every game:
(gnome-settings-daemon:7755): GnomeDesktop-WARNING **: Failed to load PNP ids: Datei >>/usr/share/hwdata/pnp.ids<< konnte nicht geöffnet werden: Datei oder Verzeichnis nicht gefunden

Means in english; File >>....<< could not be opened. File or Folder not found.

Am i right,that this is a kernel-related problem? But steamos is a fresh install and well upgradet.

**Comment by silelmot** [comment]
ok. no idea? Shall i post it in steamos-forum at the steamcommunity?

**Comment by ProfessorKaos64** [comment]
@silelmot it wouldn't hurt. Sorry just been busy. I haven't forgot about you. Thank you for your patience. As you know, wine is not always predictable as it is, and doing this in SteamOS is even harder.

**Comment by silelmot** [comment]
ok. i managed it. maybe you can add in your guide, that the scripts in /usr/bin shall get all rights?
after i chmod755 them, they work fine now. :+1:

**Comment by ProfessorKaos64** [comment]
Sure @silelmot , i'll ensure that the user checks for executable permissions. They should have already been there, as they are in the repo file, but it's good to make sure. got it.
