### ISSUE TITLE
Game window launches behind overlay.

### ISSUE THREAD

**Issue by thehack** [ProfessorKaos64/SteamOS-Tools#121]
Hi, thanks for sharing your work. I was able to install Rocket League via your tutorial, but it launches (unavailable) behind in the main window.

I was able to test it in Desktop mode by doing a little trick which shows all open windows, but of course I cant configure my controller in Desktop mode.

If you have any advice, I'd love to hear it. 

I'm using the Brewmaster version and haven't updated to the beta client.

**Comment by ProfessorKaos64** [comment]
This even happens to me if I were to install Steam for Windows on other distros and play Rocket League. I always had to ALT+TAB to it, which due to how the compositor works with SteamOS, may not be possible. It may be though, via "grabbing" the spawned window. I'm not sure how, but those that frequent this repository may have some ideas. This title is due out relatively soon, so it may just be best to way patiently, vs going through a lot of effort to make this work when it may be due up soon.

**Comment by thehack** [comment]
In case anyone else is trying to make this work, I've gotten a bit further. After a bit of guessing and experimenting I found out that I could get the game screen to pop-up reliably in desktop-mode (on steam os) by altering the setup in wine configuration like so:

![screen shot 2016-02-01 at 2 40 52 pm](https://cloud.githubusercontent.com/assets/6495/12733874/246dea40-c8f2-11e5-8809-72d287777e0c.png)

Under the in-game video options, I have also selected 'full-screen'. I am not sure if that makes a difference.

This means that you can play the game in desktop mode with a keyboard and 'sort-of' play it with a controller, but not well, as there aren't enough keybindings. The goal is to be able to play it in 'big picture' so that the controller works as it should. Currently, when I launch in big-picture-mode, the game launcher launches under a loading screen and grabs the mouse, and the only way to recover is to reboot.

**Comment by thehack** [comment]
The game should be launching in Linux within the next month, but in any case, I wanted to update that it plays reliably in SteamOS under WINE/PlayOnLinux, now. I'm using this launcher: https://github.com/ProfessorKaos64/SteamOS-Tools/blob/brewmaster/launchers/wine-pol-launchers/SonicAdventure2. The game id for line 28 is 252950. To fix the problem of the game intermittently launching under an overlay I increased the sleep time on line 51 to 5.

**Comment by ProfessorKaos64** [comment]
Than you for the update @thehack , much appreciated. I
