### ISSUE TITLE
The Dark Mod for SteamOS

### ISSUE THREAD

**Issue by ProfessorKaos64** [ProfessorKaos64/SteamOS-Tools#126]
Effort in progress to package TDM.  I've read the [compilation guide](http://wiki.thedarkmod.com/index.php?title=The_Dark_Mod_-_Compilation_Guide), but it's woefully old, whereas the [Radiant editor](http://wiki.thedarkmod.com/index.php?title=DarkRadiant_-_Compiling_in_Linux) is updated for the latest distro variants. You'll note near the end of the build log where things got wrong. The fork contains a debian folder for packaging.

I IMMENSELY appreciate any help anyone can give. I would very much like to host this for SteamOS-Tools.

* [Mirror of 2.03 code with scons patch per wiki](https://github.com/ProfessorKaos64/tdm)
* [useful compiling thread 1](http://forums.thedarkmod.com/topic/15289-ubuntu-1310-64-bit-and-32-bit-libs/)
* [zlib patch 1](http://bugs.thedarkmod.com/view.php?id=4198)
* [The Dark Mod forum post request that was made](http://forums.thedarkmod.com/topic/17743-building-tdm-on-debian-8-steamos-tdm-203/)

Main errors are related to zlib:
```
cc1: warning: command line option '-fpermissive' is valid for C++/ObjC++ but not for C
In file included from /usr/include/png.h:536:0,
                 from lib/devil/il_png.c:21:
/usr/include/zlib.h:86:5: error: unknown type name 'z_const'
     z_const Bytef *next_in;     /* next input byte */
     ^
/usr/include/zlib.h:86:19: error: expected ':', ',', ';', '}' or '__attribute__' before '*' token
     z_const Bytef *next_in;     /* next input byte */
                   ^
In file included from /usr/include/zlib.h:34:0,
                 from /usr/include/png.h:536,
                 from lib/devil/il_png.c:21:
/usr/include/zlib.h:1025:29: error: unknown type name 'z_const'
 typedef unsigned (*in_func) OF((void FAR *,
                             ^
/usr/include/zlib.h:1029:33: error: unknown type name 'in_func'
 ZEXTERN int ZEXPORT inflateBack OF((z_streamp strm,
                                 ^
In file included from /usr/include/png.h:536:0,
                 from lib/devil/il_png.c:21:
/usr/include/zlib.h:1349:32: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'Z_ARG'
 ZEXTERN int ZEXPORTVA gzprintf Z_ARG((gzFile file, const char *format, ...));
                                ^
/usr/include/zlib.h:1748:15: error: unknown type name 'z_crc_t'
 ZEXTERN const z_crc_t FAR * ZEXPORT get_crc_table    OF((void));
               ^
/usr/include/zlib.h:1758:44: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'Z_ARG'
 ZEXTERN int            ZEXPORTVA gzvprintf Z_ARG((gzFile file,
                                            ^
scons: *** [build/release/game/lib/devil/il_png.os] Error 1
scons: building terminated because of errors.
debian/rules:8: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 2
make[1]: Leaving directory '/tmp/buildd/tdm-2.0.2+git+bsos1'
debian/rules:5: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by ProfessorKaos64** [comment]
Update, it compiled!

````
Showing contents of: /home/desktop/build-tdm-temp: 

tdm-2.0.2
tdm_2.0.2+git+bsos1-1_amd64.build
tdm_2.0.2+git+bsos1-1.debian.tar.xz
tdm_2.0.2+git+bsos1-1.dsc
tdm_2.0.2+git+bsos1-1_i386.changes
tdm_2.0.2+git+bsos1-1_i386.deb
tdm_2.0.2+git+bsos1-1_source.changes
tdm_2.0.2+git+bsos1.orig.tar.gz
```

**Comment by not83** [comment]
Mean!

**Comment by ProfessorKaos64** [comment]
However, it does not run, so there is much more it seems to "figure out".

```
TDM 2.02 #5994 linux-x86 Feb 26 2016 02:14:31
found interface lo - loopback
found interface eth0 - 192.168.11.152/255.255.255.0
Found Intel CPU with Hyper-Threading enabled, features: MMX SSE SSE2 SSE3 CMOV
tdm using generic code for SIMD processing.
no 'darkmod' directory in exe path /usr/games/tdm, skipping
WARNING: using hardcoded default base path
------ Initializing File System ------
Current search path:
  /usr/games/tdm
File System Initialized.
--------------------------------------
Unknown command 'vid_restart'
idRenderSystem::Shutdown()
I18NLocal: Shutdown.
Sys_Error: Couldn't load default.cfg
About to exit with code 1
```

**Comment by ProfessorKaos64** [comment]
Moving thedarkmod.x86 and the .pak file, along with the entire resultant build folder into $HOME, produces:

```
desktop@steamos:~/darkmod$ ./thedarkmod.x86 
TDM 2.02 #5994 linux-x86 Feb 26 2016 02:14:31
found interface lo - loopback
found interface eth0 - 192.168.11.152/255.255.255.0
Found Intel CPU with Hyper-Threading enabled, features: MMX SSE SSE2 SSE3 CMOV
tdm using generic code for SIMD processing.
------ Initializing File System ------
Current search path:
  /home/desktop/darkmod/
  /home/desktop/darkmod/tdm_game02.pk4 (2 files)
File System Initialized.
--------------------------------------
Unknown command 'vid_restart'
idRenderSystem::Shutdown()
I18NLocal: Shutdown.
Sys_Error: Couldn't load default.cfg
About to exit with code 1
```

**Comment by ProfessorKaos64** [comment]
I can confirm, this *does* work. after running the updater and installing the previous package I made (which does compile TDM, but does not add all the assets given by the updater. The approach that I think will work, is to convert what I have into a "virtual package" that provides the needed dependencies, then runs the updater as a post install step.

**Comment by ProfessorKaos64** [comment]
The package should hit brewmaster_testing tonight. 

Notable changes / modifications:

* `thedarkmod` is essentially a virtual package with a few tricks to it
* modifications done were a bit hacky, so it there is anyone that knows better, a PR is more than welcome at [SteamOS-Tools Packaging](https://github.com/ProfessorKaos64/SteamOS-Tools-Packaging)
* `/usr/games/thedarkmod` is a symbolic link to either
 * `/usr/share/games/darkmod/thedarkmod.x86`
 * `/home/steam/darkmod/thedarkmod.x86`
 * This is due to the base install of / on SteamOS being 10 GB, where /usr sits.
 * Other Debian distro's (which this should also run on), should not have such a small / partition
* Desktop file
* Artwork
* After the `thedarkmod` is installed, the "online updater" will fire off and grab the game files. If a game file exists, it will be checked against the server version (standard behavior)

Now, there are still efforts to compile the entire project (which I have figured out most of). However, this approach seemed to work fairly well on Debian 8 and SteamOS. If you do inspect debian/control, you'll notice a large batch of 32-bit libraries. The Dark Mod is a 32 bit application still (I believe there are future plans to move to 64 bit on the forums), so these are required.
