### ISSUE TITLE
Retroarch - Steam Controller - B Button always crash

### ISSUE THREAD

**Issue by pogipants** [ProfessorKaos64/SteamOS-Tools#129]
Hi all, I saw this issue on reddit but it seemed dead, and did not find anything on the issues here. So I started my own issue. Pertinent post: https://www.reddit.com/r/SteamOS/comments/3zabsn/retroarch_malfunctioning_with_steam_controller/

* Steam client version: 1459463254
* SteamOS version: 2.0 update 1:2.64
* Opted into Steam client beta?: NO
* Opted into SteamOS beta?: NO
* Have you checked for updates in Settings > System?: YES

#### Please describe your issue in as much detail as possible:
I expect to use the b button to select options in Retroarch

#### Steps for reproducing this issue:

1. Open Retroarch with Steam controller via SteamOS
2. Press B
3. Crash

#### Note:

Log: https://gist.github.com/ProfessorKaos64/a0e3595f6f98c814fe7ad65fc31e03bf

#### Progress Tracker (Please do not remove)

- [ ] Investigate issue
- [ ] Fix committed / Resolution

**Comment by ProfessorKaos64** [comment]
Having trouble reproducing this. I would try purging the package and reinstalling after updating your package lists. Please list how you installed RetroArch etc, with the exact comands.

**Comment by ProfessorKaos64** [comment]
I found out what was going on, incorrect path to the joypad autoconfig files location. I was able to reproduce this. A new package will go out later today that sets some defaults for the config file

**Comment by ProfessorKaos64** [comment]
This is a problem only* with the Stem Controller. After much testing, there isn't much I can do. I opened an upstream case here:

https://github.com/libretro/retroarch-joypad-autoconfig/issues/225
