### ISSUE TITLE
Issues building Kodi 17 / latest master tree CORE DUMP / SEGFAULT

### ISSUE THREAD

**Issue by ProfessorKaos64** [ProfessorKaos64/SteamOS-Tools#131]
Current attempt to build a package for Krypton. Previously, i'd hook into the https://github.com/xbmc/xbmc-packaging from the base script in the [xbmc repo](https://github.com/xbmc/xbmc/tree/master/tools/Linux/packaging) mk-debian-package. Up to and including Jarvis, this packaging repo worked. Now I get cmake errors with dpkg-source. I've reviewed [an old thread](http://forum.kodi.tv/showthread.php?tid=195267&highlight=old+version+is+plain+file) and ensured directories were clean etc. The symlinked files in question were created 3 months ago in the master branch.

**note:** I am using pbuilder, disregard dependencies in the log.

```
    dpkg-source -b kodi-source
    dpkg-source: info: using source format `3.0 (quilt)'
    dpkg-source: info: building kodi using existing ./kodi_17.0a1-Krypton~git20160501.1203-bee0201.orig.tar.gz
    dpkg-source: error: cannot represent change to project/cmake/scripts/ios/install.cmake:
    dpkg-source: error:  new version is symlink to ../darwin/install.cmake
    dpkg-source: error:  old version is plain file
    ...
```

## Links

Forum post: http://forum.kodi.tv/showthread.php?tid=272185
log: http://sprunge.us/AcKA
verbose bash output / verbose dh: http://sprunge.us/OjHi
build script: https://github.com/ProfessorKaos64/Libre...ld-kodi.sh
Reddit thread: https://www.reddit.com/r/kodi/comments/4han1x/packaging_kodi_krypton_on_linux/

**Comment by ProfessorKaos64** [comment]
Build now successful by resolving symlinks with [read-links.sh](https://github.com/ProfessorKaos64/LibreGeek-Packaging/blob/brewmaster/kodi/read-links.sh). The original tarball is created with the `-h` flag, which resolves those links and archives the file with the tarball. This conflicts with the original source.

The Debian package builds using packaging from the [Nightly PPA builds](https://launchpad.net/~team-xbmc/+archive/ubuntu/xbmc-nightly), but will segfault with this hard stop:


Kodi crash log:
http://sprunge.us/KiaM

**Comment by ProfessorKaos64** [comment]
Contents of linux.xml (installed to /usr/share/kodi/system/settings/linux.xml) and comparison:

**Kodi 16 build**

PENDING

**Kodi 17 build**  

```
<?xml version="1.0" encoding="utf-8" ?>
  <section id="system">
    <category id="display">
      <group id="1">
        <setting id="videoscreen.fakefullscreen">
          <visible>false</visible>
        </setting>
      </group>
    </category>
  </section>
</settings>

**Comment by wsnipex** [comment]
this got broken in https://github.com/xbmc/xbmc/commit/ee40239798bf61229ee7859037ef3a194e074b3b
see https://github.com/xbmc/xbmc/issues/9752 for the fix

**Comment by ProfessorKaos64** [comment]
@wsnipex, thank you for weighing in on this. I have the old generated xml file form Jarvis, with the tag intact. I'll try a master build today.

**Comment by ProfessorKaos64** [comment]
[xbmc/9753](https://github.com/xbmc/xbmc/pull/9753) Submitted to resolve symlink issue.

**Comment by ProfessorKaos64** [comment]
xml error in crash log gone, investigating more crash log info (this time with gdb installed):
http://sprunge.us/KPJd

**Comment by ProfessorKaos64** [comment]
@wsnipex , found out this was due to libegl-nvidia0 missing that provides libEGL_nvidia.so*. Can you speculate why this is? I added this as a requirement to Retroarch and Kodi 17 in my test repository and it solved both segfault issues.
