### ISSUE TITLE
Attempt to run on Ubuntu 16.04

### ISSUE THREAD

**Issue by peppy6582** [ProfessorKaos64/SteamOS-Tools#140]
#### Your system information

* Steam client version: Built: Jun 23 2016 Package Version: 1466649529
* SteamOS version: Not SteamOS, Ubuntu 16.04
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamOS beta?: [Yes/No] No
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.
I am trying to run this on Ubuntu 16.04.  Got everything installed, including emulators, but it hangs when I run ice-steamos and it should work, but instead I got this error:
Traceback (most recent call last):
  File "__main__.py", line 11, in <module>
    runner.run(sys.argv)
  File "/usr/share/games/ice/runners/command_line_runner.py", line 48, in run
    'emulators': options.emulators,
  File "/usr/share/games/ice/runners/ice_engine.py", line 58, in __init__
    self.users = filter(is_user_context, steam_module.local_user_contexts(self.steam))
TypeError: 'NoneType' object is not iterable

#### Steps for reproducing this issue:

1. Run on Ubuntu 16.04
2. 
3. 

#### Progress Tracker (Please do not remove)

- [ ] Investigate issue
- [ ] Fix committed / Resolution

**Comment by ProfessorKaos64** [comment]
This is designedand tested, packaged for SteamOS only. Of you have trouble, submit an issue to https://github.com/scottrice/Ice or use a PPA, if you find one. I don't have time to support multiple sisters being only one person. Ice is a project that frequently breaks or has lonstanding standing issues.

**Comment by peppy6582** [comment]
Thanks for the reply.  I appreciate the time that you have put into getting
this running on SteamOS.
