### ISSUE TITLE
retroarch-src script infinitely loops

### ISSUE THREAD

**Issue by flibitijibibo** [ProfessorKaos64/SteamOS-Tools#141]
#### Your system information

* Steam client version: Latest as of June 28 2016
* SteamOS version: Brewmaster 270
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
After building retroarch-src via desktop-software.sh, I ran /usr/bin/retroarch-src and found that it was freezing my system. After looking at the process list with ps -ef, I found this...

![retroloop](https://cloud.githubusercontent.com/assets/1396814/16427046/aa6d7a3c-3d39-11e6-91a7-7b27fd17e56a.png)

#### Steps for reproducing this issue:

1. Install RetroArch from src via desktop-software.sh
2. Run retroarch-src via terminal, desktop, Big Picture, etc.
3. Wait!

#### Progress Tracker (Please do not remove)

- [x] Investigate issue
- [x] Fix committed / Resolution

**Comment by ProfessorKaos64** [comment]
Thank you for the report. I will definitely fix this. I keep this script around for those that maybe want to build off the master tree, otherwise the retroarch package in the repository follows the stable release model.

**Comment by flibitijibibo** [comment]
Had a look, I think I know what's happening.

RetroArch works just fine, but at some point this happens, roughly in this order:

- `retroarch-src/libretro-super/retroarch/retroarch` binary is compiled
- symlink `/usr/bin/retroarch-src` points to retroarch binary
- `/usr/bin/retroarch-src` gets overwritten with the script found in this repository

So what probably needs fixing is the script install; the symlink can be skipped and the script source can just point to the retroarch binary.

**Comment by ProfessorKaos64** [comment]
Did some cleanup on the install areas, but i'll double check more of this soon. I scratched the binary linking and just instruct the script to copy it to `/usr/bin` instead. Launching `retroarch-src` will call RetroArch with the appropriate configuration file.

Appreciate the heads up. I do most things nowadays via a debian package, vs. manual steps like this.
