### ISSUE TITLE
[ Request ] Making It Easy to Know Which Games Work With WINE

### ISSUE THREAD

**Issue by ekianjo** [ProfessorKaos64/SteamOS-Tools#145]
There are probably quite a few sources out there to collect that information, but most of it is not 100% relevant to SteamOS (because of a number of differences in libraries) - it would be great to start collecting data related to WINE games working under SteamOS, and keeping such information under json or xml format so that we can query that information in a script as well. This kind of json/xml document could be hosted on these github pages, and updated as we test more and more stuff.

**Comment by ProfessorKaos64** [comment]
I would suggest just adding test data to [WineHQ](https://appdb.winehq.org/objectManager.php?sClass=version&iId=2739) and use SteamOS as the distribution. This is too large a scope. I will include this in the wiki once I make a general WINE page. Example above is for WOW.
