### ISSUE TITLE
missing dolphin-emu package

### ISSUE THREAD

**Issue by dcbaker** [ProfessorKaos64/SteamOS-Tools#147]
#### Your system information

* Steam client version:
* SteamOS version: brewmaster
* Opted into Steam client beta?: [Yes/No] no
* Opted into SteamOS beta?: [Yes/No] no
* Have you checked for updates in Settings > System?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
After a fresh install using the configure-repos.sh script as described in the wiki, steamos-ice fails to install with missing dependency dolphin-emu.

After looking at the repository itself, I think that either the main package didn't upload (the data package is there) or the dolphin-emu-master package should provide dolphin-emu, but does not. I'm unsure of which (or perhaps both) is the problem.

#### Steps for reproducing this issue:

1. On a fresh steamos download configure-repos.sh
2. ./configure-repos.sh
3. apt update; apt upgrade
4. apt install ice-steamos

#### Progress Tracker (Please do not remove)

- [x] Investigate issue
- [x] Fix committed / Resolution

**Comment by ProfessorKaos64** [comment]
Somehow....the data package is in the stable repo, and the main package in the testing repo. Copied the main package to the stable repo. Can you try again?

**Comment by dcbaker** [comment]
Yeah, I'll give it a go tonight when I get home.

I figured it was probably something like that.

**Comment by dcbaker** [comment]
Still not working, and I don't see the non-data package in the repo when I inspect manually inspect the repo (http://packages.libregeek.org/SteamOS-Tools/pool/games/d/dolphin-emu/) I'm still only seeing the data package

**Comment by ProfessorKaos64** [comment]
Rebuilding this again now, making sure .changes lists all the appropriate files. Sorry about this.

**Comment by ProfessorKaos64** [comment]
Update again in 5 min and try now. Syncing to repo as I type.

**Comment by ProfessorKaos64** [comment]
tested this today, should be good to go now.

**Comment by dcbaker** [comment]
Sorry, I was away over the weekend. Just wanted to confirm that it is in fact working, thanks for fixing this.
