### ISSUE TITLE
Fresh install - dolphin_emu unmet dependencies 

### ISSUE THREAD

**Issue by silelmot** [ProfessorKaos64/SteamOS-Tools#148]
I installed Steam OS fresh  with the img of stephensons rocket,
i than installed steamos-tools the default way with git clone
now i tried installing dolphin-emu with "ap-get install dolphin-emu" and i get thesee errors:

 dolphin-emu : Hängt ab von: libavcodec-ffmpeg56 (>= 7:2.4) soll aber nicht installiert werden oder
                              libavcodec-ffmpeg-extra56 (>= 7:2.4) soll aber nicht installiert werden
               Hängt ab von: libavformat-ffmpeg56 (>= 7:2.4) soll aber nicht installiert werden
               Hängt ab von: libavutil-ffmpeg54 (>= 7:2.4) soll aber nicht installiert werden
               Hängt ab von: libswscale-ffmpeg3 (>= 7:2.4) soll aber nicht installiert werden
               Hängt ab von: dolphin-emu-data (= 5.0+git+bsos-1) aber 5.0+git+bsos1-1 soll installiert werden

its german, but its the classic unmet dependencies error.... so...any advice , what to do?

**Comment by silelmot** [comment]
ok. my fault. its dolphin-emu-master to install

**Comment by ProfessorKaos64** [comment]
dolphin emu master is a very old PPA backport. Let me rebuild dolphin-emu.  The versioning on ffmpeg changed. You'll see this after 'apt-get update` and 'apt-cache policy ffmpeg `

**Comment by ProfessorKaos64** [comment]
Oh no, i'm wrong, dolphin-emu-master is the more up to date version I build off of the latest master tree. I am updating that today. dolphin-emu is the stable release. Both are being updated now.

**Comment by ProfessorKaos64** [comment]
Should be fixed for both the stable dolphin-emu and unstable dolphin-emu-master.
