### ISSUE TITLE
PS4 ds4drv script gone?

### ISSUE THREAD

**Issue by Enigma0** [ProfessorKaos64/SteamOS-Tools#152]
#### Your system information

* Steam client version: latest
* SteamOS version: n/a (Ubuntu GNOME 16.04.1)
* Opted into Steam client beta?: n/a
* Opted into SteamOS beta?: n/a 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
The YouTube video here (https://www.youtube.com/watch?v=LKBiznMLFj4) mentions using a script in utilities but it's no longer there in the main branch. I've installed it manually but it isn't set up as a service and also doesn't work to emulate xbox controls: https://github.com/chrippa/ds4drv/issues/97

#### Steps for reproducing this issue:

1. Missing ps4 setup script in `utilities`

#### Progress Tracker (Please do not remove)

- [x] Investigate issue
- [x] Fix committed
- [ ] Confirmed Resolution

**Comment by ProfessorKaos64** [comment]
The PS3/PS4 situation used to be where you needed to use some kind of script to make it easier. However, especially  with the case with PS4 Controllers, they work "out of the box". I rarely have time to make youtube videos these days, but not to say I won't in the future. 

I haven't updated ds4drv in a while, but I have noticed activity in Chirpa's repository. I'll take a look at it soon. Can you not just pair in the SteamOS settings area and configure the inputs? If it is from a game perspective, and you want to mimic an Xbox controller, then I understand. The script you reference was only used before ds4drv was packaged. All it did was build ds4drv and enable the service.

When I repackage ds4drv, i'll see if I can enable the service as a post install step or at least produce some helpful output on what to do.

**Comment by Enigma0** [comment]
Pairing works fine. The DS4 even works in Steam Big Picture for navigating. It just doesn't work in any game. I was curious to see what you had happening in the script to see if there's something I'm missing to get it working.

**Comment by ProfessorKaos64** [comment]
Yes, I will repackage and test ds4drv this week. [This is the old script](https://raw.githubusercontent.com/ProfessorKaos64/SteamOS-Tools/d62257ee25e6487b9a8888ebdd57337a3f1f197e/utilities/pair-ps4-bluetooth.sh) if you are curious.

**Comment by ProfessorKaos64** [comment]
The latest version should stop ds4drv.service, install, and enable/start the service after. I have to head to bed, but I'll test it tomorrow at some point. There was an issue with the service being installed correctly.

**Comment by ProfessorKaos64** [comment]
I tested the new package over SSH this morning. Make sure you are installing `ds4drv_0.5.1+20160829git+bsos-1`. I checked the status of the service after installation. I haven't had time to do physical controller tests yet with a game.

**Comment by Enigma0** [comment]
Cool. Yeah I'm running 5.1. Seems like you were just using the default configuration but thanks for linking the script. Still not working as an xbox controller for me and it's likely due to a player 1/player 2 glitch that the ds4drv does.
