### ISSUE TITLE
Desktop-Software.sh install webapp fails

### ISSUE THREAD

**Issue by dmbreton** [ProfessorKaos64/SteamOS-Tools#153]
#### Your system information

* Steam client version: 1471977975
* SteamOS version:  SteamOS 2.0 1:2.87
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
Running the command  "sudo desktop-software.sh install webapp" exits after pressing "c" to continue after the debian repo check

I did a git pull to get the latest from the SteamOS Tools and updated the steam client and steam os.   I have also uninstalled/reinstalled the repos to make sure there were no issues there and got the same results

#### Steps for reproducing this issue:

1.  Running the command  "sudo desktop-software.sh install webapp" 
2.  press "c" and enter at prompt for repo check
3.  Scripts exits

#### Progress Tracker (Please do not remove)

- [x] Investigate issue
- [x] Fix committed
- [x] Confirmed Resolution

**Comment by dmbreton** [comment]
Looks like this was a typo on my end

"sudo desktop-software.sh install webapp" should have been "sudo desktop-software.sh webapp install"  Still having issues with the packages not being found, but I will close this one and reopen another if I cannot figure that out

**Comment by ProfessorKaos64** [comment]
No, it's install "module name" like you had it. I will look at this soon. 

On August 29, 2016 3:38:14 PM EDT, dmbreton <notifications@github.com> wrote:
>Looks like this was a typo on my end
>
>"sudo desktop-software.sh install webapp" should have been "sudo
>desktop-software.sh webapp install"  Still having issues with the
>packages not being found, but I will close this one and reopen another
>if I cannot figure that out
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ProfessorKaos64/SteamOS-Tools/issues/153#issuecomment-243231384

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dmbreton** [comment]
Oh I thought I had it backwards after reading the script.  I will keep playing with it

**Comment by dmbreton** [comment]
When I run a "sudo apt-get  update" i do not see the libregeek repo.  I reran the configure-repos.sh and that did not seem to have an effect.  I also saw the "steamos-tools-repo" pkg while searching and installed it, but that did not seem to fix anything either.

**Comment by dmbreton** [comment]
Let me know if there is anything else I can do

**Comment by ProfessorKaos64** [comment]
It was removed at some point since most everything is available in the browser. I will put the function hook back in. Give me a bit.

**Comment by ProfessorKaos64** [comment]
Also, you are not following the readme. It would be

`./scriptname` not 'sudo this or that.

**Comment by dmbreton** [comment]
How do you get a fullscreen in the browser?  If that is an option I may be able to go that route.  

Trying to make my steam box the default media box and getting these web app well integrated in a must.

Needs to pass the wife test... ;-)

**Comment by ProfessorKaos64** [comment]
I'll explain once I fix things. I'm still at work :P

On August 29, 2016 3:56:58 PM EDT, dmbreton <notifications@github.com> wrote:
>How do you get a fullscreen in the browser?  If that is an option I may
>be able to go that route.  
>
>Trying to make my steam box the default media box and getting these web
>app well integrated in a must.
>
>Needs to pass the wife test... ;-)
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ProfessorKaos64/SteamOS-Tools/issues/153#issuecomment-243236552

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ProfessorKaos64** [comment]
Should be back up and running now. I will recheck the var names / case a bit later when I have more time. I will also review the wiki page for webapps, which you can review here:

https://github.com/ProfessorKaos64/SteamOS-Tools/wiki/Web-Apps

As for the Steam browser, you can full screen the video if it has a button for it (like Youtube does), but not every web page as you would F11 with Windows or common browsers.

**Comment by dmbreton** [comment]
Doesn't seems to completely work.  It creates the shortcuts,  but it says I am missing an external repository.  I had to manually add the libregeek repo and the debian repos are there.  I will take a look again later today.

**Comment by ProfessorKaos64** [comment]
Idk why you say './configure-rep is.sh' does nothing. That is what will setup the repository. If in doubt, re I've those packages before hand, as well as from /var/cache/apt/archives. (the repo packages).

**Comment by jonbitzen** [comment]
PK - 

I think there is a problem in the desktop-software.sh script, at lines 614-615:

		echo -e "\nProceeding to configure-repos.sh.sh"
		"${SCRIPTDIR}/configure-repos.sh.sh"

The extra .sh should probably be removed?  When I removed it the script seemed able to proceed.

Thanks,

jonbitzen

**Comment by ProfessorKaos64** [comment]
Good catch, I'll check and take care of this today. 

On August 31, 2016 12:48:32 AM EDT, jonbitzen <notifications@github.com> wrote:
>PK - 
>
>I think there is a problem in the desktop-software.sh script, at lines
>614-615:
>
>		echo -e "\nProceeding to configure-repos.sh.sh"
>		"${SCRIPTDIR}/configure-repos.sh.sh"
>
>The extra .sh should probably be removed?  When I removed it the script
>seemed able to proceed.
>
>Thanks,
>
>jonbitzen
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ProfessorKaos64/SteamOS-Tools/issues/153#issuecomment-243657468

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
