### ISSUE TITLE
OpenPHT missing shared libraries

### ISSUE THREAD

**Issue by jonbitzen** [ProfessorKaos64/SteamOS-Tools#154]
#### Your system information

* Steam client version: Built September 20 2016 18:21:07 / 1474415843
* SteamOS version: 2.0 update 1:2.87
* Opted into Steam client beta?: [Yes/No] no
* Opted into SteamOS beta?: [Yes/No] no
* Have you checked for updates in Settings > System?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:

Some MP3 media files do not run on the OpenPHT client for SteamOS.  I searched the OpenPHT log file and found the following errors:
13:16:36 T:139752730449920   DEBUG: CPlayerCoreFactory::GetPlayers: added 3 players
13:16:36 T:139752730449920   DEBUG: Mimetype: audio/mpeg3
13:16:36 T:139752730449920   DEBUG: SECTION:LoadDLL(libmad.so.0.2.1)
13:16:36 T:139752730449920   DEBUG: Loading: libmad.so.0.2.1
13:16:36 T:139752730449920   ERROR: Unable to load libmad.so.0.2.1, reason: libmad.so.0.2.1: cannot open shared object file: No such file or directory
13:16:36 T:139752730449920   DEBUG: Dll libmad.so.0.2.1 was not found in path
13:16:36 T:139752730449920   DEBUG: SECTION:LoadDLL(libmad.so.0.2.1)
13:16:36 T:139752730449920   DEBUG: Loading: libmad.so.0.2.1
13:16:36 T:139752730449920   ERROR: Unable to load libmad.so.0.2.1, reason: libmad.so.0.2.1: cannot open shared object file: No such file or directory
13:16:36 T:139752730449920   DEBUG: Dll libmad.so.0.2.1 was not found in path
13:16:36 T:139752730449920   ERROR: CAudioDecoder: Unable to Init Codec while loading file plexserver://b94372eb5622a47e33a18772f3ddf411fa6b40b9/library/parts/1180/1471120104/file.mp3
13:16:36 T:139752730449920 WARNING: PAPlayer::QueueNextFileEx - Failed to create the decoder
13:16:36 T:139752730449920   ERROR: Playlist Player: skipping unplayable item: 0, path [plexserver://b94372eb5622a47e33a18772f3ddf411fa6b40b9/library/parts/1180/1471120104/file.mp3]

When I went to look into the  OpenPHT installation in /opt/openpht/bin I found the following items with broken softlinks (black background, red text):

libass.so   libmpeg2.so  librtmp.so       libva.so         
libcec.so   libogg.so    libshairplay.so  libvdpau.so     
libcurl.so  libplist.so  libtiff.so       libvorbisenc.so 
libmad.so   libpng.so    libva-glx.so     libvorbis.so

This is on a very fresh (one day old install of steamos / steamos tools).
Before installing openpht and the webapps I ran the configure-repos.sh script.

Is it possible there are broken package dependencies?

#### Steps for reproducing this issue:

1. 
2. 
3. 

#### Progress Tracker (Please do not remove)

- [x] Investigate issue
- [x] Fix committed
- [ ] Confirmed Resolution

**Comment by ProfessorKaos64** [comment]
Hmmm, OpenPHT hasn't been changed in a while, but perhaps I overlooked a runtime dep/lib. I'll check this out today.

**Comment by ProfessorKaos64** [comment]
I am going to correct the build to install to the /usr prefix, as it should. I see these missing libs:

```
        linux-vdso.so.1 (0x00007ffcc7c6f000)
        libavcodec.so.56 => not found
        libavformat.so.56 => not found
        libavutil.so.54 => not found
        libpostproc.so.53 => not found
        libswscale.so.3 => not found
        libavfilter.so.5 => not found
        libswresample.so.1 => not found
``

...using ldd, so i'll fix that and get a package up in a few hours.

**Comment by ProfessorKaos64** [comment]
Can you try install libmad0? That provides that library. If that works, I'll include it in the build.

**Comment by ProfessorKaos64** [comment]
Something happened in the builds with openpht 1.6.2. I amended the path to the libs in openpht.sh under /usr/bin/openpht.sh. You should notice with `openpht 1.6.2+20160925git+bsos-6` (building now, give it 30 minutes to build/upload), that the splash now says OpenPHT (an open source Plex client) with the RasPlex > "arroow" in-between. See how this build works for you. This build system uses CDBS (common Debian build system), so it's not quite straightforward.

**Comment by jonbitzen** [comment]
PK,


I'll try to have a look at the changes you made this weekend.  I really appreciate all your effort, and I will look at the updates soon.


Good catch on 1.6.2 by the way, I made that change by hand Sunday afternoon when I couldn't get 1.5 to work.  I probably should have submitted a bug.


Also, if I get a chance, I was thinking about adding a spotify web-player option to the web apps menu - does that sound like something you'd want in there?  I've always put it in manually the last couple of times I've reinstalled, and maybe others would like it too.


Thanks,


Jon


________________________________

**Comment by ProfessorKaos64** [comment]
I can add spotify, but if you want to submit a PR, that is fine too.
