### ISSUE TITLE
pair-PS4-bluetooth.sh not available

### ISSUE THREAD

**Issue by gree303** [ProfessorKaos64/SteamOS-Tools#155]
I wanted to try the PS4 controller script. Somehow only PS3 is available. Are they the same? Thanks

**Comment by ProfessorKaos64** [comment]
There is this wiki page:

https://github.com/ProfessorKaos64/SteamOS-Tools/wiki/Pairing-PS4-controllers

I don't promote this, as SteamOS has it's own native pairing in the setting menu, that is why I don't have the script around for it.

See: #152

**Comment by Enigma0** [comment]
Sadly, PS4/DS4 is super broken still:

- https://github.com/ValveSoftware/SteamOS/issues/511
- https://github.com/ValveSoftware/SteamOS/issues/513
- https://github.com/chrippa/ds4drv/issues/97

**Comment by ProfessorKaos64** [comment]
Well, I can restore that code then, even though it doesn't do a whole lot beyond what the ds4drv package does.
