### ISSUE TITLE
Wiki: RetroArch "tested / known working cores" link broken

### ISSUE THREAD

**Issue by mactyr** [ProfessorKaos64/SteamOS-Tools#157]
At https://github.com/ProfessorKaos64/SteamOS-Tools/wiki/Retroarch there is a link under "Tested / known working cores" (url: https://github.com/ProfessorKaos64/SteamOS-Tools/edit/testing/docs/Retroarch-Testing-Checklist.md) that takes me to a "page not found". The same bad link is found in the steam community post at https://steamcommunity.com/groups/steamuniverse/discussions/1/618460171325507240/

#### Progress Tracker (Please do not remove)

- [ ] Investigate issue
- [ ] Fix committed
- [ ] Confirmed Resolution

**Comment by ProfessorKaos64** [comment]
I must have started that ages ago, but lost the page in a commit / removal. I unfortunately do not have time to maintain a working core list. Most, if not all should work fine (package installations, not online updater which is from upstream buildbot). I'll likely just cut this section out unless there is a strong objection.
