### ISSUE TITLE
Wrong retro core in emulators.txt for SNES

### ISSUE THREAD

**Issue by CrazySpence** [ProfessorKaos64/SteamOS-Tools#158]
SNES games just blanked out when running so I went and checked the emulators.txt and it is looking for libretro_snes9x_next.so when libretro_snes9x2010.so is what was installed. A broken symlink was there for the missing core as well.

This was after a fresh install and setup of ice-steamos 

I changed the file to point to the existing core and it worked fine, more of an fyi 

- [x] Investigate issue
- [x] Fix committed
- [ ] Confirmed Resolution

**Comment by ProfessorKaos64** [comment]
Hmmm. I know the snes9x core was transitioned to the new lib, but possibly I missed the lib name. Could you list the command you listed so I can test before I update the core package? I am updated the entire set (if upstream has updated) of core packages today. I wonder what the core updater pulls down (if used).

**Comment by CrazySpence** [comment]
to test if you do ls -l /usr/lib/libretro/ you should see a red broken link for snes9x_next to /usr/lib/x64/libretro it does have a SNES core but it's snes9x2010 but the config.txt uses /usr/lib/libretro and the old lib

**Comment by ProfessorKaos64** [comment]
I should be able to get to this soon this week. I am working to update the mame/mess core, taking some tweaking. It's possible the updated core info package will define things.

**Comment by ProfessorKaos64** [comment]
I see the broken link and am looking at this now. Where is config.txt located? I did updated the core info package, but before I go any further, I want to check the files you are looking at. If this is still a problem, I can rename the core during after build time.

**Comment by CrazySpence** [comment]
/etc/ice/config.txt and probably also /etc/ice/emulators.cfg

**Comment by CrazySpence** [comment]
correction /etc/ice/emulators.txt

**Comment by ProfessorKaos64** [comment]
I see the issue with the link file in the package. Update libretro-snes9x-next and check again when you have time. Corrected the linking. I have to fix catsfc in the same manor next.
