### ISSUE TITLE
Libregeek repository not being added when running configure-repo.sh

### ISSUE THREAD

**Issue by 79Strykr** [ProfessorKaos64/SteamOS-Tools#160]
Intel Nuc
* Steam client version: Oct 13 2017
* SteamOS version: 2.0 build 1:2.87
* Opted into Steam client beta?: [No] 
* Opted into SteamOS beta?: [No] 
* Have you checked for updates in Settings > System?: [Yes]

Fresh install of SteamOS on intel nuc and trying to install kodi via SteamOS tools. apt-get cannot find kodi package. Seems that the libregeek repository is not being added when running the configure repos script.
any help would be appreciated, not really strong with linux.  

#### Steps for reproducing this issue:

1. Fresh install of SteamOS
2. git clone of SteamOS tools
3. run ./configure-repos.sh
4. When adding repos receive following errors:
"Connecting to packages.libregeek.org (packages.libregeek.org)|104.28.25.77|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2016-11-23 21:44:10 ERROR 403: Forbidden." 
5.  Then recevie following errors:
"dpkg: error processing archive libregeek-archive-keyring-latest.deb (--install):
 cannot access archive: No such file or directory
Errors were encountered while processing:
 libregeek-archive-keyring-latest.deb
dpkg: error processing archive steamos-tools-repo-latest.deb (--install):
 cannot access archive: No such file or directory
Errors were encountered while processing:
 steamos-tools-repo-latest.deb"
6. run apt-get install kodi and receive error "unable to locate package Kodi"

#### Progress Tracker (Please do not remove)

- [x] Investigate issue
- [x] Fix committed
- [ ] Confirmed Resolution

**Comment by ProfessorKaos64** [comment]
Pleas check again, there was an issue with the sync script yesterday.

**Comment by 79Strykr** [comment]
Thanks, all good now
