### ISSUE TITLE
Can't install Minecraft

### ISSUE THREAD

**Issue by linuxgaming** [ProfessorKaos64/SteamOS-Tools#181]
#### Your system information

* Steam client version: 1546909276
* SteamOS version: 2.166
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

Installing Minecraft through `sudo apt install minecraft` fails on the unmet openjdk-8-jre dependency (only openjdk-7-jre is in the repo). I added jessie-backports to sources.list and tried to install openjdk-8-jre but this in turn fails on the too old ca-certificates-java package.

#### Steps for reproducing this issue:

1. sudo apt install minecraft

#### Progress Tracker (Please do not remove)

- [x] Investigate issue
- [x] Fix committed
- [x] Confirmed Resolution

**Comment by mdeguzis** [comment]
This does lead to problems with packages that depend on openssl, so it is up to you if you want to remove jessie-backports after this install or not. 

```
The following packages have unmet dependencies:
 lgogdownloader : Depends: openssl (= 1.0.1t-1+deb8u2) but 1.0.1t-1+steamos2+deb8u9+bsos1 is to be installed
                  Depends: libssl1.0.0 (= 1.0.1t-1+deb8u2) but 1.0.1t-1+steamos2+deb8u9+bsos1 is to be installed
```

This has been already reported upstream at Valve, but I continue to have this issue: https://github.com/ValveSoftware/SteamOS/issues/557

You can fix this by:
```
sudo apt-get install -t jessie-backports openssl
```
... for instance to fix this particular issue.

**Comment by linuxgaming** [comment]
Thank you, your instructions allowed me to install java 8 and minecraft, as well as run the game in the latest version (1.13.2)! :-)

I also tried running the version with the new launcher, sadly it doesn't run, saying:
 ./launcher: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./launcher)
./launcher: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./launcher)

So it seems that SteamOS/jessie gcc libraries are just too old... but it is not that important as long as the old launcher is supported.

**Comment by mdeguzis** [comment]
Hi mmm, well the "launcher" is just a JAR file. If the above cannot be fixed (not at home right now), then I would have to locate the old one and test that.

**Comment by linuxgaming** [comment]
The new (current) launcher is actually a bash script + ELF binary.
https://launcher.mojang.com/download/Minecraft.deb
https://launcher.mojang.com/download/Minecraft.tar.gz
https://minecraft.gamepedia.com/Minecraft_launcher

So to reiterate, installing and playing minecraft from SteamOS-Tools repo works well now, however it is based on the old launcher (java -jar Minecraft.jar). Meanwhile, manually downloaded *current* launcher doesn't work. Not really an issue with SteamOS-Tools though, sorry for the confusion...
