### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by HereInPlainSight** [ProfessorKaos64/SteamOS-Tools#40]
After following the basic install instructions, libretro gets installed to /usr/lib/libretro, owned by root.

When attempting to add other cores, they failed to install, presumably because retroarch is running under the 'steam' user when launched through Steam.

As an addendum, after copying the libretro directory into the steam user's directory (and changing over config files, since I didn't want to remove or change the original installation), I was not only able to get new cores via the interface, Mednafen PSX (which had not been working for me before) was working after as well.

**Comment by ProfessorKaos64** [comment]
> After following the basic install instructions, libretro gets installed to /usr/lib/libretro, owned by root.

That is expected for anything under `/usr/lib` I believe standard implementations of libretro put cores in this location. See [this link](http://emulation-general.wikia.com/wiki/Using_RetroArch) as some general indication.

```
Next you need to locate the directory in which the libretro cores are stored. They should have been saved in the directory /usr/lib/libretro. You can check this by entering the command
```

I tried the core updater, but I will try cores "not installed" today after a complete dry run. Let me do a fresh install of SteamOS and see what I have with the latest master branch, i'll report back if the behavior matches what you are describing. 

Thanks!

**Comment by ProfessorKaos64** [comment]
Just did a fresh install. With my `scph5501.bin` BIOS file in the ROMs dir for the Steam user. If you want to try from scratch, go ahead. Otherwise just take note that I have added permissions cleanup on the Retroarch post-install config actions.

**Comment by HereInPlainSight** [comment]
Very belated update, here, sorry.  I did a full reinstall of my SteamOS, ran your stuff immediately after bringing up SSH, and everything seems fine, so I'm not exactly sure where the original problem came from, but a full wipe did seem to resolve it, so that's that, I suppose.

Thank you for working on this, it's very appreciated and helpful.

**Comment by ProfessorKaos64** [comment]
No problem! I'll do my best to make things work here.
