### ISSUE TITLE
Method to swap out xpad with xbodrv for web apps

### ISSUE THREAD

**Issue by ProfessorKaos64** [ProfessorKaos64/SteamOS-Tools#48]
A command such as 

```
sudo rmmod xpad
sudo xboxdrv --mouse &
```
Will load a basic mouse setup for your controller to control a web app (A to click). However, if anyone has a way to swap xpad back in and terminate xboxdrv **cleanly**, please let me know, or submit a PR. Also, the commands above require exceptions for the commands be made via `visudo`, which I want to avoid.

Current desktop skeleton file can be found [here](https://github.com/ProfessorKaos64/SteamOS-Tools/blob/master/cfgs/web-cfgs/skel/Default-Launch.sh)

**Comment by LemonTVnz** [comment]
https://code.google.com/p/jkeys/
You can use python/pygame to read a joystick/gamepad and generate key/mouse press/clicks

Updating to start chrome in kiosk mode with site mappings might be a decent workaround

**Comment by ProfessorKaos64** [comment]
Hmm interesting, i'll try and take a look at this today. Thank you!

**Comment by ProfessorKaos64** [comment]
Added new antimicro package rebuilt from Ryochan7's Git repository, added configurations for common controllers. See commit 797dc69
