### ISSUE TITLE
libSDL2-2.0.so.0 error

### ISSUE THREAD

**Issue by Igor1201** [ProfessorKaos64/SteamOS-Tools#53]
Antimicro wasn't working because libSDL2-2.0.so.0 wasn't found on system.
A simple `sudo apt-get install libsdl2-2.0-0 libsdl2-2.0-0:i386` fixed this issue for me.

**Comment by ProfessorKaos64** [comment]
Hmm, never got that, I will check this out on a fresh install tonight. Regardless, I will temporarily add this to the pre-requisite are of this install section, and also rebuild antimicro with new dependencies for this, if true. Thank you very much for the report.

**Comment by Igor1201** [comment]
You are welcome! Thank YOU for the awesome project, btw.

**Comment by ProfessorKaos64** [comment]
Ha, thank you very much. I just like to tinker with bash and love to game. New build package upload to [libregeek](http://www.libregeek.org/SteamOS-Extra/utilities/) called "antimicro_2.14+git20150602-SteamOS_amd64.deb ". I started to record source build parameters to keep track of any I do. You can see that so far for antmicro [here](https://github.com/ProfessorKaos64/SteamOS-Tools/blob/master/extra/source-build-tracking.md). I did a quick install test of the pacakge after removing the application depdendencies and antimicro. Let me know if this works for you if you decide to test yourself.

**Comment by ProfessorKaos64** [comment]
tested several times to ensure repackaged deb works. Closing.
