### ISSUE TITLE
emulation does not install correctly

### ISSUE THREAD

**Issue by bhdwiel** [ProfessorKaos64/SteamOS-Tools#63]
I'm trying to install the emulators with

$ ./desktop-software.sh install emulation

This is the output of log.txt

desktop@steamos:~/SteamOS-Tools$ cat log.txt 
[2J#####################################################
Loading script modules
#####################################################
Loaded module emulators-from-src.shinc
Loaded module emulation.shinc
Loaded module retroarch-post-cfgs.shinc
Loaded module extra-pkgs.shinc
Loaded module retroarch-from-src.shinc
Loaded module ue4-from-src.shinc
Loaded module ue4.shinc
Loaded module web-apps.shinc
==> Updating system, please wait...
Hit http://repo.steampowered.com alchemist Release.gpg
Hit http://repo.steampowered.com precise Release.gpg
Hit http://http.debian.net wheezy-backports Release.gpg
Hit http://repo.steampowered.com alchemist Release
Hit http://http.debian.net wheezy-backports Release
Hit http://repo.steampowered.com precise Release
Hit http://http.debian.net wheezy-backports/main amd64 Packages/DiffIndex
Hit http://http.debian.net wheezy-backports/main i386 Packages/DiffIndex
Hit http://repo.steampowered.com alchemist/main Sources
Hit http://http.debian.net wheezy-backports/main Translation-en/DiffIndex
Hit ftp://mirror.nl.leaseweb.net wheezy Release.gpg
Hit http://repo.steampowered.com alchemist/contrib Sources
Hit ftp://mirror.nl.leaseweb.net wheezy Release
Hit http://repo.steampowered.com alchemist/non-free Sources
Hit ftp://mirror.nl.leaseweb.net wheezy/main Sources
Hit http://repo.steampowered.com alchemist/main amd64 Packages
Hit ftp://mirror.nl.leaseweb.net wheezy/contrib Sources
Hit http://repo.steampowered.com alchemist/contrib amd64 Packages
Hit ftp://mirror.nl.leaseweb.net wheezy/non-free Sources
Hit http://repo.steampowered.com alchemist/non-free amd64 Packages
Hit ftp://mirror.nl.leaseweb.net wheezy/main amd64 Packages
Hit http://repo.steampowered.com alchemist/main i386 Packages
Hit ftp://mirror.nl.leaseweb.net wheezy/contrib amd64 Packages
Hit http://repo.steampowered.com alchemist/contrib i386 Packages
Hit ftp://mirror.nl.leaseweb.net wheezy/non-free amd64 Packages
Hit http://repo.steampowered.com alchemist/non-free i386 Packages
Hit ftp://mirror.nl.leaseweb.net wheezy/main i386 Packages
Hit ftp://mirror.nl.leaseweb.net wheezy/contrib i386 Packages
Hit ftp://mirror.nl.leaseweb.net wheezy/non-free i386 Packages
Hit ftp://mirror.nl.leaseweb.net wheezy/contrib Translation-en
Hit ftp://mirror.nl.leaseweb.net wheezy/main Translation-en
Hit ftp://mirror.nl.leaseweb.net wheezy/non-free Translation-en
Hit http://repo.steampowered.com precise/steam Sources
Hit http://repo.steampowered.com precise/steam amd64 Packages
Hit http://repo.steampowered.com precise/steam i386 Packages
Ign http://repo.steampowered.com alchemist/contrib Translation-en_US
Ign http://repo.steampowered.com alchemist/contrib Translation-en
Ign http://repo.steampowered.com alchemist/main Translation-en_US
Ign http://repo.steampowered.com alchemist/main Translation-en
Ign http://repo.steampowered.com alchemist/non-free Translation-en_US
Ign http://repo.steampowered.com alchemist/non-free Translation-en
Ign http://repo.steampowered.com precise/steam Translation-en_US
Ign http://repo.steampowered.com precise/steam Translation-en
Reading package lists...
==> Validating packages...
gdebi-core package status: [OK]
dosbox package status: [OK]
stella package status: [OK]
mednafen package status: [OK]
fceu package status: [OK]
==> Attempting zsnes automatic package installation...
Reading package lists...
Building dependency tree...
Reading state information...
zsnes:i386 is already the newest version.
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 libsdl1.2debian:i386 : Depends: libasound2:i386 (>= 1.0.16)
Reading package lists...
Building dependency tree...
Reading state information...
Correcting dependencies... Done
The following extra packages will be installed:
  libasound2:i386
Suggested packages:
  libasound2-plugins:i386
The following NEW packages will be installed:
  libasound2:i386
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
21 not fully installed or removed.
Need to get 0 B/460 kB of archives.
After this operation, 1,315 kB of additional disk space will be used.
Do you want to continue [Y/n]? (Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 97926 files and directories currently installed.)
Unpacking libasound2:i386 (from .../libasound2_1.0.25-4+bsos7_i386.deb) ...
dpkg: error processing /home/desktop/cache_temp/libasound2_1.0.25-4+bsos7_i386.deb (--unpack):
 trying to overwrite shared '/usr/share/alsa/alsa.conf', which is different from other instances of package libasound2:i386
Errors were encountered while processing:
 /home/desktop/cache_temp/libasound2_1.0.25-4+bsos7_i386.deb
==> Could not install or remove ALL packages from the
alchemist repositories, wheezy sources, or alternative
source lists you have configured.
Please check log.txt in the directory you ran this from.
Failure occurred on package: zsnes

**Comment by ProfessorKaos64** [comment]
Are you on brewmaster? Emulation will just install some emulators, per the main readme. To get Retroarch, as an "all in one option" use emulation-src as the package type.

See:

**Comment by bhdwiel** [comment]
I'm on alchemist, but I'll try using emulation-src like you suggested.

**Comment by ProfessorKaos64** [comment]
ok, i'll check this out today when I get some time. That install type should work.

**Comment by ProfessorKaos64** [comment]
Just did an install of the emulation type package now, should work. I am going to rename it to "emulators" to avoid some confusion, and emulation-src to retroarch-src.

**Comment by ruskininja** [comment]
I think since you've updated this, you forgot to update all of the references to emulation.shinc.

Used your post on reddit to try and get the kiosks to work in Steam Big Picture and yesterday it was working, but after a bunch of screwups on my end, I reinstalled my OS and tried again today and am getting the error "Unable to find module /home/user/SteamOS-Tools/scriptmodules/emulation"

This happens specifically when I run "./desktop-software.sh install webapp" in command line.

I've went ahead and changed emulators.shinc to emulation.shinc for the initial install, but you probably need to update all references to emulation.shinc

**Comment by ProfessorKaos64** [comment]
Ah that's the nodule import. I'll get this fixed tomorrow morning or via mobile tonight. Sorry about that!

On August 11, 2015 8:08:11 PM EDT, ruskininja <notifications@github.com> wrote:
>I think since you've updated this, you forgot to update all of the
>references to emulation.shinc.
>
>Used your post on reddit to try and get the kiosks to work in Steam Big
>Picture and yesterday it was working, but after a bunch of screwups on
>my end, I reinstalled my OS and tried again today and am getting the
>error "Unable to find module
>/home/user/SteamOS-Tools/scriptmodules/emulation"
>
>This happens specifically when I run "./desktop-software.sh install
>webapp" in command line.
>
>I've went ahead and changed emulators.shinc to emulation.shinc for the
>initial install, but you probably need to update all references to
>emulation.shinc
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ProfessorKaos64/SteamOS-Tools/issues/63#issuecomment-130116915

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ruskininja** [comment]
Yeah, no biggie.  Changing the name did the trick for the install.  Just frustrated me a little that I ran the same exact steps as I did yesterday and it yielded different results, couldn't figure out why for a little bit.

**Comment by ProfessorKaos64** [comment]
I've had that error before. I think it has to do with some kind of package conflict. Not sure. That is for stopping by at any rate

On August 11, 2015 8:16:51 PM EDT, ruskininja <notifications@github.com> wrote:
>Yeah, no biggie.  Changing the name did the trick for the install. 
>Just frustrated me a little that I ran the same exact steps as I did
>yesterday and it yielded different results, couldn't figure out why for
>a little bit.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ProfessorKaos64/SteamOS-Tools/issues/63#issuecomment-130117923

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ProfessorKaos64** [comment]
Fixed, also keep in mind webapps works just on Alchemist right now. If I could get Kodi back on (it's install been broken for a bit), I could try those addons, but alas not now due to that.

**Comment by ProfessorKaos64** [comment]
names changed, docs updated. closing unless otherwise needed
