### ISSUE TITLE
Cores fail to compile. Alsa dependency needed.

### ISSUE THREAD

**Issue by gglass** [ProfessorKaos64/SteamOS-Tools#65]
I ran across this issue when trying to build retroarch to launch mame. Our conversation is documented here:
https://www.reddit.com/r/SteamOS/comments/3hqfk9/anyone_else_having_issues_launching_mame/

When making the cores, compilation failed due to not having the alsa dependency. I fixed by installing the libasound2-dev package and then re-making /home/desktop/retroarch-src/libretro-super/libretro-mame/Makefile.libretro

**Comment by ProfessorKaos64** [comment]
I know exactly why this happened. I did refactor some dependencies from the [lists](https://github.com/ProfessorKaos64/SteamOS-Tools/tree/alchemist/cfgs/software-lists) I use for some modules and installs. I likely did not test of a fully clean installation. I usually go off of what [libretro](https://github.com/libretro/RetroArch/wiki/Compilation-guide-%28Linux%29) specifies, however, this explains why some mame core variants failed to build at times.

Fixed in commits: a671eaf, e564de4, and 0c12877. This can be closed once fully tested on either end.

**Comment by gglass** [comment]
I must not be fully understanding something. After running the Makefile.libretro myself, it generates a mame_libretro.so. I copied this to /usr/lib/libretro/ and then tried to run RetroArch-Src in steamui. Unfortunately, it still didn't run. Again, no error or anything as before. I am rebuilding using ./desktop-software.sh install emulation-src mame one more time just to make sure.

Is there something I need to do to start from scratch again? 

I also noted that parts of the installation were throwing errors because of the absense of "unzip" and "bc" which I installed from packages before rebuilding.

**Comment by ProfessorKaos64** [comment]
That should be `./desktop-software install retroarch-src` Based on that line, it pulls the packages needed from the list I linked above, which includes bc, but not unzip, which I thought was included in SteamOS, so i'll add that. I am building this now, and will try later tonight or sunday. I used this heavily in Alchemist, so I likely just need a few fixes, if that.

**Comment by gglass** [comment]
No worries. I'm about to have to unplug for the weekend, so I'll be back
around on Monday.

I have to admit, its been fun working through this. If there's anything you
need help with, let me know. I haven't worked in C in ages, but I am a web
developer by day and don't mind getting my hands dirty with stuff. If
there's anything I can help with, let me know!

**Comment by ProfessorKaos64** [comment]
Sorry, this was my mistake, the alchemist hook was not updated [this line](https://github.com/ProfessorKaos64/SteamOS-Tools/blob/alchemist/desktop-software.sh#L668) did read "emulation-src". Sloppy mistake. Don't worry, I'm committed to this :)

**Comment by ProfessorKaos64** [comment]
```
I have to admit, its been fun working through this. If there's anything you need help with, let me know. I haven't worked in C in ages, but I am a web developer by day and don't mind getting my hands dirty with stuff. If there's anything I can help with, let me know
```
Well to be honest, just good ideas, and help to make this repo better overall. The web apps (Google chrome in kiosk mode) seems broken on Brewmaster, so I've been trying to figure that out. Also, kodi's install is broken. If you find something you'd like to work on that you want to add, that is great. The main aim of this repo is to offer nice "bolt on" operations for use with official Valve releases, otherwise folks could use VaporOS or Stephenson's rocket.

I have some ideas for things to add, but yea, if you every want to, I always have the #steamos IRC chat up, so just msg me there or PM me on IRC, or here.

**Comment by ProfessorKaos64** [comment]
Tested on Brewmaster last night and Alchemist (via VMware) this morning. Seems to work fine in both cases now.

**Comment by gglass** [comment]
I may need to wipe it all and start over. Thanks for keeping me posted!

**Comment by gglass** [comment]
I've removed /usr/lib/libretro completely as well as the SteamOS-Tools
repo. I'm trying to start over from scratch as best I can.

After doing this, I cloned the repo again. When I run ./desktop-software.sh
insall emulation-src using the updated source, I keep getting:

> ==> Validating packages...
> dpkg-query: no packages found matching emulation-src
> emulation-src package status: [Not found]
> ==> Attempting emulation-src automatic package installation...
> Reading package lists...
> Building dependency tree...
> Reading state information...
> E: Unable to locate package emulation-src

The installation halts after this. Did something get renamed? Do I need to
do something else to update my sources?

**Comment by gglass** [comment]
I realize I made a mistake. I didn't notice that I was supposed to be running ./desktop-software.sh install retroarch-src. I was still trying ./desktop-software.sh install emulation-src. My bad. Maybe need to update: https://github.com/ProfessorKaos64/SteamOS-Tools/blob/testing-alchemist/docs/retroarch-info.md.

**Comment by ProfessorKaos64** [comment]
test alchemist should not be used, it should be noted in the main readme what the main branches are to be used.

**Comment by gglass** [comment]
Yeah, I was unfamiliar with the github ui. In one of your first posts you
mentioned moving all of the docs to the wiki, but I only just found the
wiki you were talking about today. Just me being ignorant. I'm compiling
the correct sources now! Thanks for the help. I think this ticket can
probably be closed as I didn't run into the alsa issue again.

**Comment by ProfessorKaos64** [comment]
well, once you're fully up and running, close it then, make sure things are 100% good. Maybe I will start packaging things (less updated) in the coming weeks. Maybe :P

**Comment by gglass** [comment]
Got it up and running. This can be safely closed now! Thanks again for all the help and patience.
