### ISSUE TITLE
Can't run sudo in test chroot, not owned by root

### ISSUE THREAD

**Issue by ProfessorKaos64** [ProfessorKaos64/SteamOS-Tools#68]
I've been following https://wiki.debian.org/chroot [1] , and using a post install script after building the chroot. For some reason after sudo is installed, and even if I put corrections into it to own /usr/bin/sudo as root, it fails with "sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set". I have commands to change the ownership and suid in the post install script, but it seems to have no effect. I can run these commands manually and sudo will work, but not in this automated post-install launch.

I first have this script run:  
https://github.com/ProfessorKaos64/SteamOS-Tools/blob/brewmaster/utilities/build-test-chroot.sh [2]

Then, per the end of that first script, kick off a post install:  
https://github.com/ProfessorKaos64/SteamOS-Tools/blob/brewmaster/utilities/chroot-post-install.sh [3]

**Comment by Ryochan7** [comment]
You are undoing the file changes after the chroot-post-install.sh script finishes. The end of build-test-chroot.sh will force /usr/bin/sudo and related files, as well as the reset of the chroot, to be owned by $USER. Why is a recursive chown performed? I can understand possibly having the / directory owned by $USER but that doesn't seem like a good idea for the whole chroot to be owned by $USER.

**Comment by ProfessorKaos64** [comment]
Omg that's my mistake. Duh me. Feel like an idiot now. Per other guides I should still mount the proc / dev on the host fstab, correct?

On September 5, 2015 2:26:29 PM EDT, Travis Nickles <notifications@github.com> wrote:
>You are undoing the file changes after the chroot-post-install.sh
>script finishes. The end of build-test-chroot.sh will force
>/usr/bin/sudo and related files, as well as the reset of the chroot, to
>be owned by $USER. Why is a recursive chown performed? I can understand
>possibly having the / directory owned by $USER but that doesn't seem
>like a good idea for the whole chroot to be owned by $USER.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ProfessorKaos64/SteamOS-Tools/issues/68#issuecomment-137983869

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
