### ISSUE TITLE
Add a working build of Kodi to your repository?

### ISSUE THREAD

**Issue by SplodeyDope** [ProfessorKaos64/SteamOS-Tools#81]
Kodi installation is broken on SteamOS right now.  Most people considering dedicating a PC to their living room for SteamOS are going to see the lack of media capability as a deal breaker.  Now, I know this isn't your responsibility but I kept seeing your name pop up every time I researched an issue with SteamOS.  You could probably get this done and no one else seems to be working on it.  Help us ProfessorKaos64, you're our only hope!

**Comment by ProfessorKaos64** [comment]
This is more certainly on my radar. It is in the top 5 things I want to get done. I hope to get something into the brewmaster_testing release area by Monday.Yea my name seems to pop up more often (probably Google spying on Steam Universe forum posts ha). I'll label this an enhancement request and start to look at this. I have a build script started, but I am unsure where I left of.

**Comment by SplodeyDope** [comment]
Awesome, thank you!

**Comment by ProfessorKaos64** [comment]
the install type 'kodi-src' works now, but I will keep looking into packaging it if I can find out how.

**Comment by ProfessorKaos64** [comment]
I'm getting a bit closer to getting a debian package to test. Just need to check on a missing library "libbluray-dev".

**Comment by ProfessorKaos64** [comment]
I was able to get to the Debian Lintian stage, where final packaging occurs. A few more steps closer to getting packages built :)

**Comment by SplodeyDope** [comment]
Fantastic!  :D

**Comment by ProfessorKaos64** [comment]
Kodi is now in brewmaster_testing. After a minimum 1 week breakin period, it will move to the stable repository

https://github.com/ProfessorKaos64/SteamOS-Tools/wiki/Kodi
https://steamcommunity.com/groups/steamuniverse/discussions/1/523898291499139752/

**Comment by ProfessorKaos64** [comment]
Kodi 15 isengard is in my brewmaster repo,. Kodi 16 Jarvis is in brewmaster_testing.
