### ISSUE TITLE
request: Add Plex home theater

### ISSUE THREAD

**Issue by dawnson** [ProfessorKaos64/SteamOS-Tools#82]
It would be nice to have a PHT client instead of using kodi with a plugin

**Comment by ProfessorKaos64** [comment]
There is plex available in the libgreek repos. After adding the repos (.e.g. add-debian-repos), you can specify `sudo apt-get install plexhometheater`. Does this not work for you?

**Comment by ProfessorKaos64** [comment]
`plexhometheater`  is available via the libregeek repos.  closing
