### ISSUE TITLE
Fresh install added Deb Repos and SOS Tools key signing error

### ISSUE THREAD

**Issue by madmodderx** [ProfessorKaos64/SteamOS-Tools#83]
sources.list:
`deb ftp://mirror.nl.leaseweb.net/debian/ jessie main contrib non-free
deb-src ftp://mirror.nl.leaseweb.net/debian/ jessie main contrib non-free

deb ftp://mirror.nl.leaseweb.net/debian/ jessie-backports main contrib non-free
deb-src ftp://mirror.nl.leaseweb.net/debian/ jessie-backports main contrib non-free

deb http://packages.libregeek.org/SteamOS-Tools/ brewmaster main
deb-src http://packages.libregeek.org/SteamOS-Tools/ brewmaster main

deb http://packages.libregeek.org/SteamOS-Tools/ brewmaster_testing main`
results in a public key dealy thats not mentioned anywhere in the wiki
sudo apt-get update:
`Reading package lists... Done
W: GPG error: http://packages.libregeek.org brewmaster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8106E72834C589A7
W: GPG error: http://packages.libregeek.org brewmaster_testing InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8106E72834C589A7`

I can't seem to install git properly either to grab your tools.

Fresh install, just this morning. going to try turning off and on to see it this solves the problem...

**Comment by ProfessorKaos64** [comment]
I will look at this.  For some reason, even though I have checks in for the gpg keys, they don't load the first time around. From the github repo, run `utilities/gpg_import.sh KEYNUMBER` to import it. Ill get to this tomorrow. 

On September 19, 2015 9:45:41 PM EDT, madmodderx <notifications@github.com> wrote:
>sources.list:
>`deb ftp://mirror.nl.leaseweb.net/debian/ jessie main contrib non-free
>deb-src ftp://mirror.nl.leaseweb.net/debian/ jessie main contrib
>non-free
>
>deb ftp://mirror.nl.leaseweb.net/debian/ jessie-backports main contrib
>non-free
>deb-src ftp://mirror.nl.leaseweb.net/debian/ jessie-backports main
>contrib non-free
>
>deb http://packages.libregeek.org/SteamOS-Tools/ brewmaster main
>deb-src http://packages.libregeek.org/SteamOS-Tools/ brewmaster main
>
>deb http://packages.libregeek.org/SteamOS-Tools/ brewmaster_testing
>main`
>results in a public key dealy thats not mentioned anywhere in the wiki
>sudo apt-get update:
>`Reading package lists... Done
>W: GPG error: http://packages.libregeek.org brewmaster InRelease: The
>following signatures couldn't be verified because the public key is not
>available: NO_PUBKEY 8106E72834C589A7
>W: GPG error: http://packages.libregeek.org brewmaster_testing
>InRelease: The following signatures couldn't be verified because the
>public key is not available: NO_PUBKEY 8106E72834C589A7`
>
>I can't seem to install git properly either to grab your tools.
>
>Fresh install, just this morning. going to try turning off and on to
>see it this solves the problem...
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ProfessorKaos64/SteamOS-Tools/issues/83

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by madmodderx** [comment]
I fixed my git install issue. just mistyped 'sudo apt-get -f install'  with git at the end and fixed by removing git from the end.

**Comment by madmodderx** [comment]
Awesome not getting the key error anymore in apt-get :)

**Comment by ProfessorKaos64** [comment]
I did retest this just now from a completely blank machine (the gpg import error). Recently today, I just added a [fallback](https://github.com/ProfessorKaos64/SteamOS-Tools/blob/brewmaster/add-debian-repos.sh#L30) line of code to assume present working directory if called by itself. To always keep up to date, make sure you regularly update the repo with `git pull` when inside the git folder.
