### ISSUE TITLE
[Question][Statements] Emulators and another linux game

### ISSUE THREAD

**Issue by madmodderx** [ProfessorKaos64/SteamOS-Tools#88]
This is going to be a bunch of questions and things that I've learned from my new install.
1. In Brewmaster you can compile Stepmania from source fairly easily! (I can come up with the instructions to be translated into a script if interested)
2. The latest .deb of Dolphin from the official site works (I haven't played any games on it yet) and it doesn't have the packaging error that would uninstall it like Alchemist packages did. After ```dpkg -i``` an ```apt-get -f install``` fixes it any missing dependencies.
3. PPSSPP "installs" and works fine from it's zip/rar just need to give it a folder and a ```.desktop```
4. Have we had/seen any progress in pcsx2? I haven't been tinkering with it since my system broke, I did my clean install, and lately work.

**Comment by ProfessorKaos64** [comment]
1. I am going to try and package that today :) I heard someone requested this.
2. I should be able to rebuild that
3. Same as question 2
4. Same as question 2. 

Give me some time and I'll reply back here and I add debs to the repo. Thanks for the request!

**Comment by ProfessorKaos64** [comment]
Stepmania is in. It is added to a new dist release, so please re-run "add-debian-repos" to update first. 
```
sudo apt-get update
sudo apt-get install sm-smc
```
Others maybe be in a bit later.

**Comment by ProfessorKaos64** [comment]
`dolphin-emu` now added to brewmaster games

**Comment by ProfessorKaos64** [comment]
`ppsspp-qt` now added

**Comment by ProfessorKaos64** [comment]
`pcsx2` will not be added right now,  There are issues building the Git source and/or PPA due to the large amount of 32 bit packages needed. They conflict with almost every existing package dependency it needs on there. You may be able to just install the .deb pacakge, but if I cannot rebuild the source code and properly build against SteamOS build-packages and link against SteamOS libraries, I won't add it.

**Comment by ProfessorKaos64** [comment]
IF the baoev

**Comment by madmodderx** [comment]
Baoev?

**Comment by ProfessorKaos64** [comment]
I'm not sure what Baoev is. I closed by accident.

**Comment by madmodderx** [comment]
Yeah, pcsx2 is very unlikely to get a 64-bit support. If it doesn't make
it, I won't cry too much.
Although if I recall correctly, Can't you use multiarch to allow 32bit
repos to be ready side by side with their x64 variants?

**Comment by ProfessorKaos64** [comment]
Multiarch is on by default, and I also check for it when running the main desktop-software.sh script. I believe there is one called "Play" but it is Windows only. I will revisit PCSX2 at some point.

**Comment by madmodderx** [comment]
Thanks for everything though, I grueling appreciate it! =D

**Comment by madmodderx** [comment]
Truly*

**Comment by ProfessorKaos64** [comment]
I am glad you reminded me about Stepmania, I love that game.

**Comment by madmodderx** [comment]
If only osu! had a decent wine port for Debian... Or Linux support period.

**Comment by Ryochan7** [comment]
When compiling PCSX2, I had to compile it under a i386 chroot. It looks like you have been experimenting with pbuilder. Using pbuilder will probably be the best approach to take for getting PCSX2 built with the least amount of problems.

**Comment by madmodderx** [comment]
Actually I found a precompiled version and added dependencies until it ran
properly but I never got past setup. After that because there was a
sound/network driver that I just could never get.

**Comment by ProfessorKaos64** [comment]
I'll give pbuilder a shot soon. I almost have a handle on basic usage. If not, i'll use a chroot. @madmodderx , it's important to build the source code, rather than just using a deb from another distro. Sometimes it seems to work, but I've found it never to be a good idea.

@Ryochan7 , i'll also adjust the build-chroot script to allow either debian arch. I'll give this a shot tomorrow. I will be busy tonight I think.

**Comment by madmodderx** [comment]
I had a lot of nonos that affected my alchemist build that boned me on the
long term. Now that I'm a bit more fluent in Debian I've been a bit more
careful with how I handle these things

**Comment by ProfessorKaos64** [comment]
Reopen for PCSX2 attempts and tracking.

**Comment by ProfessorKaos64** [comment]
OK, pcsx2 snapshot is building now. I'll let you know if it builds and installs. If so, I'll add it to the repo.

**Comment by ProfessorKaos64** [comment]
I'll then try to build the current Git master tree for a brewmaster_testing variant.

**Comment by ProfessorKaos64** [comment]
pcsx2-unstable_1.3.1~git20150810 is now in the brewmaster repo. I'll package the latest git master tree for brewmaster_testing.

**Comment by Ryochan7** [comment]
Thank you for the update.

**Comment by ProfessorKaos64** [comment]
@Ryochan7 , started a build script here:
https://github.com/ProfessorKaos64/SteamOS-Tools/blob/brewmaster/utilities/build-scripts/build-pcsx2.sh

Trying a build now.

**Comment by ProfessorKaos64** [comment]
Pcsx2 latest 20151003 snapshot is in brewmaster_testing. When. Satisfied with either package, you can close out the issues ticket.

**Comment by ProfessorKaos64** [comment]
Sorry, name for latest snap is `pcsx2-unstable`

**Comment by Ryochan7** [comment]
Version 20150810 works well so I will probably stick with that version for the time being. Now I should spend a little time playing some Xenosaga. Also, I don't have permission to close this issue.
