### ISSUE TITLE
Evaluation for build of Plex Media Player 

### ISSUE THREAD

**Issue by ProfessorKaos64** [ProfessorKaos64/SteamOS-Tools#90]
While qt-5.6-alpha builds ok, mpv may not be possible. mpv is available in the Jessie repositories, but it is too old (everything for PMP has to be very up to date). Building mpv from source seems to require some packages that would remove Valve-provided packages (something I refuse to do in this repository). If a statically linked package shows up eventually in a Ubuntu PPA.  It is unknown if an mpv package from stretch or sid would work here.

Continued in #135 

See:
https://github.com/plexinc/plex-media-player/issues/62#issuecomment-151081145

**Comment by tru** [comment]
What things does mpv depend on that will collide with valves stuff?

**Comment by ProfessorKaos64** [comment]
Not at home right now, I will give you a full run down here when I do get home of all my steps involved. If I eventually get this working for SteamOS / Debian 8, i'm sure may folks will enjoy it. If I cannot now, I will wait fort the public release after the preview period to take another look. I *knew* you'd see this since Github always rats/spills the beans on you if you link an issue :)

**Comment by ProfessorKaos64** [comment]
@tru , I did not forget about this, I have just been busy. I'll report back all my steps later this evening.

**Comment by ProfessorKaos64** [comment]
@tru I actually sucessfully backported the core Qt 5.6.0 packages (base,xml,declaritive,webengine) to Jessie :) I also backported/built mpv and libmpv. However, I have one last hurdle I'm trying to add openssl support to make 3.1+, is it a matter of adding the right build dep for cmake to pick it up, or do I need to add a flag [here](https://github.com/ProfessorKaos64/LibreGeek-Packaging/blob/brewmaster/cmake/debian/rules#L24)?  I had parsed CMakeLists and tried adding a manual flag, but perhaps I am missing something. Things do compile, I just need this configuration flag / package figured out.

**Comment by tru** [comment]
create ssl.cmake and add this:
set(CMAKE_USE_OPENSSL ON CACHE BOOL "" FORCE)

Then do configure --init=ssl.cmake

**Comment by ProfessorKaos64** [comment]
that second line was what I needed, will do. Thank you very much @tru. To work up to a fully debianized version of PMP for Jessie/SteamOS will be nice.

**Comment by ProfessorKaos64** [comment]
hmm still get the same error: [log](https://gist.github.com/ProfessorKaos64/bd522fb2394a2518a19a3ea2fb071e72)

**Comment by tru** [comment]
Sorry no idea. Maybe you don't have libssl-dev installed?

**Comment by ProfessorKaos64** [comment]
Thanks for checking anyway. I don't like having to reach out to the internet during a build, but it's how it is with this project, nothing I can do about it.

**Comment by tru** [comment]
There was recently a patch that allowed the build system to use a local already downloaded web-client package. Maybe that would help you?

**Comment by ProfessorKaos64** [comment]
I'd be quite interested in that. #cmake on freenode did help clue me into the issue. Since the default rules files of Ubuntu and Debian's packaging use all system libs, this skips over using the repo bulid's curl. This in turn ignore that line you mentioned above (what I had in another line in rules). I made a var to use all system libs except curl, and got this:

```
"-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.1k") "
```

Much better :). But yes, even if this works (walking the dog next while it builds), i'd be interested to see that code. Again, many thanks for the assist.

**Comment by ProfessorKaos64** [comment]
No dice, rats. I even nixed use of system libraries, not just curl, everything built and tested with cmake's compile/test. Still got the hash mismatch when building plex :/

```
- web-client version: f61ba32
CMake Error at CMakeModules/WebClientResources.cmake:11 (file):
  file DOWNLOAD HASH mismatch

    for file: [/home/desktop/build-plex-media-player-temp/plex-media-player-1.0.6.229/src/plex-web-client-konvergo-f61ba32.cpp.tbz2]
      expected hash: [a60db1f4813dab80e5237d4c2bb3bd75d2eb3dea]
        actual hash: [da39a3ee5e6b4b0d3255bfef95601890afd80709]
             status: [22;"HTTP response code said error"]

Call Stack (most recent call first):
  src/CMakeLists.txt:100 (include)


-- Configuring incomplete, errors occurred!
See also "/home/desktop/build-plex-media-player-temp/plex-media-player-1.0.6.229/CMakeFiles/CMakeOutput.log".
See also "/home/desktop/build-plex-media-player-temp/plex-media-player-1.0.6.229/CMakeFiles/CMakeError.log".
```

**Comment by ProfessorKaos64** [comment]
Frustrating problem for sure. I drop to root in the chroot after plexnediaplayer's build fails. I cloned the cmake repo, created the SSL hook as @tru described, and fired off the build locally, installing to /usr. 

Log: http://sprunge.us/cSFS

Still get a hash mismatch building Plex. I honestly don't know how else to make it work. If bootstrap for cmake finds openssl and passes all its tests, I don't know. So close to having Debian builds of everything but* PlexMediaPlayer :/

**Comment by ProfessorKaos64** [comment]
@tru, #cmake did notice the obvious...my old issue was unsupported protocol. Now I get hash mismatch on HTTP? What could this mean? Is it an issue to report to Plex?

**Comment by ProfessorKaos64** [comment]
Related issue: https://github.com/plexinc/plex-media-player/issues/273

**Comment by ProfessorKaos64** [comment]
Sweet, the download completes, as this was fixed in the master branch and will be for future releases. Now a new error?

```
    /build/plex-media-player-1.0.6.229+git+bsos/Build/src/Version.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: shared
-- Generating done
-- Build files have been written to: /build/plex-media-player-1.0.6.229+git+bsos/Build
debian/rules:7: recipe for target 'override_dh_auto_configure' failed

```

**Comment by ProfessorKaos64** [comment]
Issues continued upstream with [plex/issue 311](https://github.com/plexinc/plex-media-player/issues/311#issuecomment-208449627).

```
2016-04-12 08:21:48 [ DEBUG ] HelperMain.cpp @ 50 - Helper ( "1.1.0.dev-7791329f" ) up and running 
2016-04-12 08:21:48 [ INFO  ] LocalJsonServer.cpp @ 33 - Listening to socket: "/tmp/pmp_pmpHelper_desktop.sock" 
2016-04-12 08:38:05 [ DEBUG ] HelperSocket.cpp @ 35 - Server connected. 
2016-04-12 08:38:05 [ DEBUG ] HelperSocket.cpp @ 46 - PMP application quit, let's wait 3 minutes and then exit 
2016-04-12 08:41:05 [ DEBUG ] HelperSocket.cpp @ 21 - Quit timer ran out, quitting... 


```

Only hard errors I see are these:

```
2016-04-12 08:14:57 [ ERROR ] InputLIRC.cpp @ 82 - LIRC Socket Error :  QLocalSocket::ServerNotFoundError 
...
2016-04-12 08:14:58 [ ERROR ] InputComponent.cpp @ 234 - Slot for host command missing, or has incorrect signature! 

```

**Comment by ProfessorKaos64** [comment]
Package built. I do not have a Plex Pass subscription. If anyone has one, and you're willing to test this package, please let me know.
