### ISSUE TITLE
Kodi frequently crashes for me

### ISSUE THREAD

**Issue by UDK450** [ProfessorKaos64/SteamOS-Tools#91]
**System Specs (Custom Built):**
CPU: Intel i5 4460
GPU: AMD Radeon HD 7870
RAM: Kingston HyperX 1600MHz, 1x8gb
SSD: Sandisk PLUS 128gb
HDD: some crappy 320gb laptop drive (nothing on it yet(
MB: GIGABYTE GA-Z97N-WIFI
PSU: Corsair CS450M (not that it matters)

**Steps:**

1. Downloaded http://repo.steampowered.com/download/brewmaster/SteamOSDVD.iso
2. Used dd if=SteamOSDVD.iso (after cd'ing to proper directory) of=/dev/sdc
3. Used automated install to wipe prior installation of SteamOS off disk and install with the preferred options
4. After installing SteamOS, entered desktop mode, and opened up a terminal, using passwd to set my password
5. sudo apt-get update
6. sudo apt-get upgrade
7. sudo apt-get install steamos-beta-repo
8. Update to the OS beta, already on client beta
9. Cloned SteamOS-Tools
10. ./add-debian-repos.sh
11. sudo apt-get update
12. sudo apt-get install kodi
13. Launch successfully in desktop mode
14. Install my preferred skin (Xperience1080) and tested another skin Chroma
15. When I clicked "Exit" in Kodi, it filed a crash log
16. Attempt to launch Kodi again (in desktop mode), and crashes
16. Attempt to launch Kodi in BPM, crashes
17. sudo apt-get purge kodi
18. cd SteamOS-Tools/
19. ./desktop-software.sh install kodi
20. Repeat steps 13-16 (except doesn't always launch on first try)

(To ensure it wasn't an issue with the skin, next time it managed to launch, I tried a different skin, still crashed while exiting)

**Crash Report**
http://pastebin.com/QNuuTss2 (I installed gdb in the hopes that a stack trace might assist the correction of this issue)

Hopefully this was indepth enough. If there are any further questions related to my case, ask away.

**Comment by ProfessorKaos64** [comment]
The only thing that stands out to me, is the AMD GPU, which I do not have a means to test against. Hopefully someone can assist with that. I will try to reproduce the exact steps, with that Kodi skin applied (I typically use ReFocus). I'll look at the log tonight as well. If anything, there may be a community member that could test this scenario under AMD hardware if you post this information to the Steam Universe group under the SteamOS discussion type.

**Comment by wsnipex** [comment]
fglrx is utter crap and not supported in kodi. It just doesn't work.

**Comment by ProfessorKaos64** [comment]
Thank you for adding to this @wsnipex , as I unfortunately do not have these cards. I'll add something to the FAQ page about fglrx.

**Comment by wsnipex** [comment]
note that software decoding(i.e. turning off vaapi and vdpau) will work fine on fglrx. Usually gaming rigs have more then enough power for that.

**Comment by ProfessorKaos64** [comment]
Ok, noted in the wiki. I should have both packages built from source (tested platform with debian packaging now), and then give mythtv a go after that. I really appreciate you weighing in wsnipex.

**Comment by ProfessorKaos64** [comment]
Per @wsnipex 's comments, closing. Of note, Kodi 16 Jarvis is now in the repository if you wish to retest.
