### ISSUE TITLE
SteamOS 1.0 -> Kodi available? Repositorys gone

### ISSUE THREAD

**Issue by silelmot** [ProfessorKaos64/SteamOS-Tools#93]
Kodi is not installable on SteamOS 1.0 Alchimist.

**Comment by ProfessorKaos64** [comment]
Built a chroot to see if this is possible for me to do. I'll see what I can do this week.

**Comment by ProfessorKaos64** [comment]
It has been a very busy week with my day to day job. I'll see if I can build it this week. No promises, since the wheezy packages may be too old.

**Comment by ProfessorKaos64** [comment]
Built the packages that are required to build Kodi. I'll let you know how I make out with the main package.

**Comment by ProfessorKaos64** [comment]
Ran into some big issues with libc6 and libguntls clashing (aka "dependency hell"). I'll get this a shot on a Debian Wheezy install tomorrow if you still are interested.  You could just use the latest Kodi/XBMC from wheezy backports.

**Comment by silelmot** [comment]
No, thanks. I bought a graphics card and installed brewmaster now.
