### ISSUE TITLE
Installation and configuration of pre-built Retroarch is a pain

### ISSUE THREAD

**Issue by petroid** [ProfessorKaos64/SteamOS-Tools#94]
While steps described at [SteamOS-Tools Wiki](http://github.com/ProfessorKaos64/SteamOS-Tools/wiki/Retroarch#installation-via-rebuilt-ubuntu-ppa-packages) are pretty easy and self-explanatory, the result is somewhat undesireable.
For instance:
- custom joypad autoconfig could not be saved via Retroarch menu
- these things could not be downloaded with Retroarch online updater
  - cores
  - assets
  - probably other things too
- command `$ source scriptmodules/retroarch-post-cfgs.shinc && rpc_configure_common` :
  - does not replace */usr/share/applications/retroarch.desktop* file with one that you ship
  - tries to configure samba even if it is not installed

The first two issues are related to default retroarch config and could be addressed by editing directories via in-app menu.

**Comment by ProfessorKaos64** [comment]
What commands did you issue so I may reproduce the side effects? It appears you used apt-get, then the source command, correct?

**Comment by petroid** [comment]
Yes, correct.

**Comment by ProfessorKaos64** [comment]
`./desktop-software.sh install retroarch` does all these steps (install via apt-get, then configure). The extra steps were removed if you chose only to use apt-get get. The explanation was corrected. Having two options (script hook with post configuration vs. just the packages) is more clear. Use the desktop-software hook if you wish to have the post configs done. I am checking the other issues as well.

**Comment by ProfessorKaos64** [comment]
Ok, it seems that the permissions/owner on /usr/lib/libretro would need changed if you installed the packages standalone. The other option is to install the cores via apt-get. I can make a correction in the post-configuration setup to correct this, and remove installing every core with desktop-software so users don't need to install all cores. That way those that use desktop-sofware.sh can still use the online updater. Those that do not, will have to use apt-get.

**Comment by ProfessorKaos64** [comment]
The permissions on the /usr/lib/libretro directory would need corrected to use the online updater. I can see if I can repackage `retroarch` to allow the steam user to use the updater.

**Comment by petroid** [comment]
That would be the best solution.
The other directory, /usr/share/libretro, is used for assets, joypad autoconfig etc. Needs permissions fixed too.

**Comment by ProfessorKaos64** [comment]
I think I have this working in a basic sense to fix the owner with a postinst file for the assets package, since that is the package that changes/dumps the files in those locations. May have something more concrete tomorrow. Once these issues are corrected under SteamOS, I'll get started working in the post configuration stuff, which takes a lower precedence.

**Comment by petroid** [comment]
Okay, I think we have this sorted out. Root permissions have to stay. Probably could close the issue. After all, editing settings allows you to use updater afterwards so it is not that bad.
Personally I think that it is a design flaw in Retroarch.

**Comment by ProfessorKaos64** [comment]
Yep things will stay as is. I may still still independently package the configure script. If you wish to use the updater, just change your directory. Thank you for your understanding. 

On November 22, 2015 11:52:53 AM EST, Peter <notifications@github.com> wrote:
>Okay, I think we have this sorted out. Root permissions have to stay.
>Probably could close the issue. After all, editing settings allows you
>to use updater afterwards so it is not that bad.
>Personally I think that it is a design flaw in Retroarch.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ProfessorKaos64/SteamOS-Tools/issues/94#issuecomment-158777687

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
