### ISSUE TITLE
Obs-Studio does not install all required dependencies

### ISSUE THREAD

**Issue by egee-irl** [ProfessorKaos64/SteamOS-Tools#95]
After installing Obs-Studio, launching it reveals the following dependencies are missing and not installed as part of the Obs-Studio package:

1. libQt5Widgets
2. libxcb-xinerama
3. libQt5X11Extras

**Comment by ProfessorKaos64** [comment]
Thanks for the report. I'll get a new package up with these added as dependencies.

**Comment by egee-irl** [comment]
Also ran into another issue but, it's an upstream (or downstream?) issue with the Obs guys - https://obsproject.com/forum/threads/steamos-arb_glx_create_context-not-supported.39476/

**Comment by ProfessorKaos64** [comment]
I just build the source code, so I'm not quite sure, but i'll read that in a bit. Should have a package live in about 15 minutes.

**Comment by ProfessorKaos64** [comment]
New package is live, `obs-studio_0.12.2+git+SteamOS2_amd64.deb`. ${shlibs:Depends}, ${misc:Depends} in the control file takes care of depends for libraries and packages, respectfully. I properly built it this time with a debian folder, rather than sloppy checkinstall.

**Comment by egee-irl** [comment]
Yup, got latest and the version is indeed 0.12.2+git+SteamOS2

**Comment by ProfessorKaos64** [comment]
Ok, see how that fares with deps. It should be fine now. When satisfied, close the issue. You can keep it open if you want until you get a response on your issue you linked. It isn't probably something I can help, but who knows :)

**Comment by egee-irl** [comment]
Reopening - found some new info.

Apparently this is a known issue with OBS 12.x and will be fixed in version 13.0 - https://obsproject.com/forum/threads/failed-to-initialize-video-unspecified-error-for-obs-linux-mint.37334/#post-171604

**Comment by ProfessorKaos64** [comment]
Being on 12.2, we have some time to wait. I will keep this open to track upstream and mark it appropriately. Keep me informed if this flies under my radar.

**Comment by ProfessorKaos64** [comment]
From now on, you can track #98
