### ISSUE TITLE
SNIS

### ISSUE THREAD

**Issue by psymin** [ProfessorKaos64/SteamOS-Tools#97]
Space Nerds In Space package request.

https://smcameron.github.io/space-nerds-in-space/

**Comment by ProfessorKaos64** [comment]
Working through some [build issues](https://github.com/smcameron/space-nerds-in-space/issues/72).

**Comment by ProfessorKaos64** [comment]
snis_20151122+git+SteamOS2 is live in the repository. I'll see if I can create some nice Steam art for the game box under BPM.  Now, when I exited snis, it kind of sat there. Let me know how you make out.
